package repository

import (
	"context"
	"errors"
	"fmt"
	"strings"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/vincommerce/backend/internal/db"
	"github.com/vincommerce/backend/internal/domain"
)

// PaymentRepository persists payment intents, wallets and payouts.
type PaymentRepository struct {
	pool *db.Pool
}

// NewPaymentRepository creates a PaymentRepository.
func NewPaymentRepository(pool *db.Pool) *PaymentRepository {
	return &PaymentRepository{pool: pool}
}

// Pool exposes the underlying pool for the rare caller that needs to run a
// statement outside any transaction.
//
// It exists for exactly one thing: recording a refund's outcome AFTER the gateway
// call, which cannot happen inside the transaction that reserved the refund. A
// narrower accessor (a QueryOnly method) would be the alternative, but it would
// still hand out the pool, and a method named for the pool is honest about what
// it gives away.
func (r *PaymentRepository) Pool() *db.Pool { return r.pool }

// Refund is a durable record of one attempt to return money to a buyer.
//
// It is a repository type rather than a domain one because it is a persistence
// concern: the id is generated by the application, the status set is the
// database's, and nothing in the business rules reads it as a value object.
type Refund struct {
	ID              string
	PaymentIntentID string
	OrderID         string
	JournalID       string
	Gateway         string
	GatewayRef      string
	Amount          float64
	Reason          string
	Status          string
	FailureReason   string
	RequestedBy     string
	RequestedAt     time.Time
	SettledAt       *time.Time
	CreatedAt       time.Time
}

// CreateRefund writes a refund row inside a caller's transaction.
//
// Written BEFORE the gateway is called, and committed in its own transaction, so
// that a crash between "we decided to refund" and "the provider confirmed" leaves
// a pending row reconciliation can resolve. The alternative -- call the provider
// first, record after -- loses the record exactly when it matters most: a refund
// the provider performed that this system never wrote down.
//
// gateway_ref is whatever the CALLER knows at the time, and that is not always
// nothing. This used to bind a literal empty string, on the reasoning that the
// provider's id for a refund "does not exist until the provider assigns one" --
// which is true when WE initiate a refund, and false for a refund the provider has
// already performed and told us about.
//
// The provider-notification path set GatewayRef from the notification's own refund
// id and watched it vanish, because the INSERT ignored the field:
//
//	RecordProviderRefund  -> refunds row, gateway_ref NULL
//	replayed webhook      -> lookup filters `AND gateway_ref IS NOT NULL`
//	                      -> no row can ever match
//
// So the replay guard was inert for a second, independent reason even once it was
// correctly scoped to a payment: the reference it matches on was never stored.
// `refundKeyFor` returns "" for a row with no reference, and the composed key
// never equals an incoming one. Honouring rf.GatewayRef costs the reserve path
// nothing, because reserveRefund leaves it empty and NULLIF still writes NULL.
func (r *PaymentRepository) CreateRefund(ctx context.Context, q Querier, rf *Refund) error {
	_, err := q.Exec(ctx, `
		INSERT INTO refunds (id, payment_intent_id, order_id, gateway, gateway_ref,
		                     amount, reason, status, requested_by, requested_at)
		VALUES ($1, $2, $3, $4, NULLIF($5, ''), $6, NULLIF($7, ''), $8,
		        NULLIF($9, '')::uuid, now())`,
		rf.ID, rf.PaymentIntentID, rf.OrderID, rf.Gateway, rf.GatewayRef,
		rf.Amount, rf.Reason, rf.Status, rf.RequestedBy)
	return err
}

// UpdateRefundStatus records the outcome of a gateway refund.
//
// Deliberately a bare UPDATE rather than a guarded state transition: the caller
// is reconciling an outcome it has already learned from the provider, and
// requiring a specific prior status would make recovery from an unexpected state
// impossible. The refund's own row is the record, and the terminal states are
// terminal because nothing transitions out of them.
func (r *PaymentRepository) UpdateRefundStatus(
	ctx context.Context, q Querier, refundID, gatewayRef, status, failureReason string, settledAt *time.Time,
) error {
	tag, err := q.Exec(ctx, `
		UPDATE refunds
		   SET status = $2,
		       gateway_ref = COALESCE(NULLIF($3, ''), gateway_ref),
		       failure_reason = NULLIF($4, ''),
		       settled_at = COALESCE($5::timestamptz, settled_at)
		 WHERE id = $1`,
		refundID, status, gatewayRef, failureReason, settledAt)
	if err != nil {
		return err
	}
	if tag.RowsAffected() == 0 {
		return domain.E(domain.KindNotFound, "REFUND_NOT_FOUND",
			"no refund with that id exists")
	}
	return nil
}

// SettleRefund marks a refund as successfully completed and links the journal
// that recorded the money movement.
//
// Inside the caller's transaction, so a settled refund and the money that moved
// for it are the same event rather than two that can disagree.
func (r *PaymentRepository) SettleRefund(
	ctx context.Context, q Querier, refundID, gatewayRef, status, failureReason string,
	settledAt *time.Time, raw []byte,
) error {
	tag, err := q.Exec(ctx, `
		UPDATE refunds
		   SET status = $2,
		       gateway_ref = COALESCE(NULLIF($3, ''), gateway_ref),
		       failure_reason = NULLIF($4, ''),
		       settled_at = COALESCE($5::timestamptz, now())
		 WHERE id = $1`,
		refundID, status, gatewayRef, failureReason, settledAt)
	if err != nil {
		return err
	}
	if tag.RowsAffected() == 0 {
		return domain.E(domain.KindNotFound, "REFUND_NOT_FOUND",
			"no refund with that id exists")
	}
	return nil
}

// RefundByID reads one refund.
func (r *PaymentRepository) RefundByID(ctx context.Context, refundID string) (*Refund, error) {
	return scanRefund(r.pool.QueryRow(ctx, refundSelect+` WHERE id = $1`, refundID))
}

// RefundsAwaitingGateway lists refunds whose outcome the provider still owns.
//
// These are the ones reconciliation polls. A refund in a terminal state is never
// returned, so a failed or manual refund does not get retried forever by a job
// that cannot tell the difference between "still working on it" and "a human has
// to do this".
func (r *PaymentRepository) RefundsAwaitingGateway(ctx context.Context, limit int) ([]*Refund, error) {
	if limit <= 0 {
		limit = 100
	}
	rows, err := r.pool.Query(ctx, refundSelect+`
		 WHERE status IN ('pending', 'submitted')
		 ORDER BY requested_at ASC
		 LIMIT $1`, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	out := []*Refund{}
	for rows.Next() {
		rf, err := scanRefund(rows)
		if err != nil {
			return nil, err
		}
		out = append(out, rf)
	}
	return out, rows.Err()
}

// RefundsForOrder lists an order's refunds, newest first.
func (r *PaymentRepository) RefundsForOrder(ctx context.Context, orderID string) ([]*Refund, error) {
	rows, err := r.pool.Query(ctx, refundSelect+`
		 WHERE order_id = $1 ORDER BY created_at DESC`, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	out := []*Refund{}
	for rows.Next() {
		rf, err := scanRefund(rows)
		if err != nil {
			return nil, err
		}
		out = append(out, rf)
	}
	return out, rows.Err()
}

// RefundsForAdmin lists refunds for the operator queue, joined with the order and
// buyer so the list is answerable without an N+1 per row.
//
// The join is the point. An operator triaging "who are we owed money to" needs
// the order number and the buyer's email in the same row; making them a second
// call per line is how a queue gets exported to a spreadsheet and the audit trail
// lost. The join is on the refund's own order_id, so it adds no fan-out and cannot
// duplicate a refund.
func (r *PaymentRepository) RefundsForAdmin(ctx context.Context, status string, limit int) ([]*domain.Refund, error) {
	if limit <= 0 || limit > 500 {
		limit = 100
	}
	rows, err := r.pool.Query(ctx, `
		SELECT rf.id, rf.payment_intent_id, rf.order_id, rf.gateway,
		       COALESCE(rf.gateway_ref, ''), rf.amount::float8, COALESCE(rf.reason, ''),
		       rf.status, COALESCE(rf.failure_reason, ''), COALESCE(rf.requested_by::text, ''),
		       rf.requested_at, rf.settled_at, rf.created_at,
		       COALESCE(o.order_number, ''), COALESCE(u.email, '')
		  FROM refunds rf
		  LEFT JOIN orders o ON o.id = rf.order_id
		  LEFT JOIN users  u ON u.id = o.buyer_id
		 WHERE ($1 = '' OR rf.status = $1)
		 ORDER BY rf.created_at DESC
		 LIMIT $2`, status, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	out := []*domain.Refund{}
	for rows.Next() {
		var d domain.Refund
		if err := rows.Scan(&d.ID, &d.PaymentIntentID, &d.OrderID, &d.Gateway,
			&d.GatewayRef, &d.Amount, &d.Reason, &d.Status, &d.FailureReason,
			&d.RequestedBy, &d.RequestedAt, &d.SettledAt, &d.CreatedAt,
			&d.OrderNumber, &d.BuyerEmail); err != nil {
			return nil, err
		}
		out = append(out, &d)
	}
	return out, rows.Err()
}

const refundSelect = `
	SELECT id, payment_intent_id, order_id, COALESCE(journal_id::text, ''),
	       gateway, COALESCE(gateway_ref, ''), amount::float8, COALESCE(reason, ''),
	       status, COALESCE(failure_reason, ''), COALESCE(requested_by::text, ''),
	       requested_at, settled_at, created_at
	  FROM refunds`

// rowScanner covers both pgx.Row and pgx.Rows, so scanRefund serves the
// single-row and multi-row paths without duplicating the column order.
type rowScanner interface {
	Scan(dest ...any) error
}

func scanRefund(row rowScanner) (*Refund, error) {
	var rf Refund
	if err := row.Scan(&rf.ID, &rf.PaymentIntentID, &rf.OrderID, &rf.JournalID,
		&rf.Gateway, &rf.GatewayRef, &rf.Amount, &rf.Reason, &rf.Status,
		&rf.FailureReason, &rf.RequestedBy, &rf.RequestedAt, &rf.SettledAt, &rf.CreatedAt); err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, domain.ErrNotFound
		}
		return nil, err
	}
	return &rf, nil
}

// CreateIntent inserts a payment intent (idempotent by key).
func (r *PaymentRepository) CreateIntent(ctx context.Context, in *domain.PaymentIntent) error {
	tag, err := r.pool.Exec(ctx, `
		INSERT INTO payment_intents (id, order_id, buyer_id, amount, currency, status, gateway,
			gateway_ref, snap_token, gateway_txn_id, redirect_url, method, idempotency_key)
		VALUES ($1, $2, $3, $4, $5, $6, $7, $8, NULLIF($9,''), NULLIF($10,''), NULLIF($11,''),
			NULLIF($12, ''), $13)
		ON CONFLICT (idempotency_key) DO NOTHING`,
		in.ID, in.OrderID, in.BuyerID, in.Amount, in.Currency, in.Status, in.Gateway,
		in.GatewayRef, in.SnapToken, in.GatewayTxnID, in.RedirectURL, in.Method, in.IdempotencyKey)
	if err != nil {
		if pgErr, ok := err.(*pgconn.PgError); ok && pgErr.Code == "23505" {
			return domain.E(domain.KindConflict, "INTENT_EXISTS", "this order already has a payment intent")
		}
		return err
	}
	if tag.RowsAffected() == 0 {
		return domain.E(domain.KindConflict, "IDEMPOTENCY_REPLAY", "intent already exists for this idempotency key")
	}
	return nil
}

// CreateIntentTx inserts a payment intent inside a caller-managed transaction.
// CreateIntentTx inserts the payment intent, snapshotting the commission rate
// card in force at CHARGE time.
//
// The snapshot is what a refund later reverses. The rate used to be read at
// escrow RELEASE time from the currently-active `platform_fees` row, so an admin
// changing the rate between the order and the delivery retroactively changed what
// the seller was paid, and a refund recomputed the fee from today's rate rather
// than reversing the fee that was actually taken. See migration 00042.
//
// The rate is read HERE rather than by the caller, deliberately. There are four
// intent-creation sites (wallet, COD, gateway, and any repair path) and reading
// the rate at each of them is a chance to forget one. A refund is the only thing
// that needs the snapshot, so the write has to be unconditional.
//
// A missing rate card is not an error: the intent is created with a zero
// snapshot and commission_computed stays false, so the refund path falls back to
// the active rate. That is strictly better than failing a checkout over a
// missing configuration row, and strictly better than the retroactive
// behaviour.
func (r *PaymentRepository) CreateIntentTx(ctx context.Context, q Querier, in *domain.PaymentIntent) error {
	// Caller-supplied snapshot wins (a caller that already knows the rate, or a
	// repair path), otherwise read the active card.
	if in.CommissionRatePct == 0 && in.CommissionRateFixed == 0 {
		if cfg, err := r.ActiveFeeTx(ctx, q); err == nil && cfg != nil {
			in.CommissionRatePct = cfg.Pct
			in.CommissionRateFixed = cfg.Fixed
		}
	}
	_, err := q.Exec(ctx, `
		INSERT INTO payment_intents (id, order_id, buyer_id, amount, currency, status, gateway,
			gateway_ref, snap_token, gateway_txn_id, redirect_url, method, idempotency_key,
			commission_computed, commission_rate_pct, commission_rate_fixed)
		VALUES ($1, $2, $3, $4, $5, $6, $7, $8, NULLIF($9,''), NULLIF($10,''), NULLIF($11,''),
			NULLIF($12, ''), $13, false, $14, $15)`,
		in.ID, in.OrderID, in.BuyerID, in.Amount, in.Currency, in.Status, in.Gateway,
		in.GatewayRef, in.SnapToken, in.GatewayTxnID, in.RedirectURL, in.Method, in.IdempotencyKey,
		in.CommissionRatePct, in.CommissionRateFixed)
	if err != nil {
		if pgErr, ok := err.(*pgconn.PgError); ok && pgErr.Code == "23505" {
			return domain.E(domain.KindConflict, "INTENT_EXISTS", "this order already has a payment intent")
		}
	}
	return err
}

// ApplyFeeTx records the derived split and marks the commission computed.
//
// The boolean is set here and nowhere else. It is the predicate the refund path
// uses to decide whether the split is authoritative; before it existed the code
// used `fee_amount == 0`, which cannot distinguish "not derived" from "derived
// and genuinely zero".
func (r *PaymentRepository) ApplyFeeTx(ctx context.Context, q Querier, intentID string, fee, sellerAmount float64) error {
	_, err := q.Exec(ctx, `
		UPDATE payment_intents
		SET fee_amount = $2, seller_amount = $3, commission_computed = true, updated_at = now()
		WHERE id = $1`, intentID, fee, sellerAmount)
	return err
}

// intentColumns are the shared SELECT columns for intent lookups.
//
// The commission snapshot columns are included here rather than read separately,
// because a refund that recomputes the split from today's settings instead of
// the rate card that was in force at charge time is a silent money bug. Having
// them in the shared projection means every reader sees the same numbers.
const intentColumns = `
	id, order_id, buyer_id, amount, currency, status, gateway,
	COALESCE(gateway_ref,''), COALESCE(snap_token,''), COALESCE(gateway_txn_id,''), COALESCE(redirect_url,''),
	COALESCE(method,''), idempotency_key,
	escrow_released_at, captured_at, refunded_at, fee_amount, seller_amount,
	commission_computed, commission_rate_pct, commission_rate_fixed,
	created_at, updated_at`

func scanIntent(row pgx.Row) (*domain.PaymentIntent, error) {
	var in domain.PaymentIntent
	err := row.Scan(&in.ID, &in.OrderID, &in.BuyerID, &in.Amount, &in.Currency, &in.Status, &in.Gateway,
		&in.GatewayRef, &in.SnapToken, &in.GatewayTxnID, &in.RedirectURL,
		&in.Method, &in.IdempotencyKey,
		&in.EscrowReleasedAt, &in.CapturedAt, &in.RefundedAt, &in.FeeAmount, &in.SellerAmount,
		&in.CommissionComputed, &in.CommissionRatePct, &in.CommissionRateFixed,
		&in.CreatedAt, &in.UpdatedAt)
	if errors.Is(err, pgx.ErrNoRows) {
		return nil, domain.ErrNotFound
	}
	if err != nil {
		return nil, err
	}
	return &in, nil
}

// IntentByOrder fetches the intent for an order.
func (r *PaymentRepository) IntentByOrder(ctx context.Context, orderID string) (*domain.PaymentIntent, error) {
	in, err := scanIntent(r.pool.QueryRow(ctx,
		`SELECT `+intentColumns+` FROM payment_intents WHERE order_id = $1`, orderID))
	if domain.Is(err, domain.KindNotFound, "") {
		return nil, domain.E(domain.KindNotFound, "NO_INTENT", "no payment intent for order")
	}
	return in, err
}

// IntentByRef fetches an intent by gateway reference.
func (r *PaymentRepository) IntentByRef(ctx context.Context, gateway, ref string) (*domain.PaymentIntent, error) {
	in, err := scanIntent(r.pool.QueryRow(ctx,
		`SELECT `+intentColumns+` FROM payment_intents WHERE gateway = $1 AND gateway_ref = $2`, gateway, ref))
	if domain.Is(err, domain.KindNotFound, "") {
		return nil, domain.E(domain.KindNotFound, "NO_INTENT", "no payment intent for reference")
	}
	return in, err
}

// IntentByKey fetches an intent by its idempotency key.
func (r *PaymentRepository) IntentByKey(ctx context.Context, key string) (*domain.PaymentIntent, error) {
	in, err := scanIntent(r.pool.QueryRow(ctx,
		`SELECT `+intentColumns+` FROM payment_intents WHERE idempotency_key = $1`, key))
	if domain.Is(err, domain.KindNotFound, "") {
		return nil, domain.E(domain.KindNotFound, "NO_INTENT", "no payment intent for key")
	}
	return in, err
}

// SetIntentStatus transitions the intent status.
func (r *PaymentRepository) SetIntentStatus(ctx context.Context, intentID, status string) error {
	return setIntentStatusOn(r.pool, ctx, intentID, status)
}

// SetIntentStatusTx transitions the intent status inside the given transaction.
func (r *PaymentRepository) SetIntentStatusTx(ctx context.Context, tx pgx.Tx, intentID, status string) error {
	return setIntentStatusOn(tx, ctx, intentID, status)
}

// SetIntentStatusGuarded transitions the intent only when its current status is
// one of the expected values; returns a conflict error otherwise. This makes
// financial state machines idempotent and replay-safe.
func (r *PaymentRepository) SetIntentStatusGuarded(ctx context.Context, intentID string, expected []string, to string) error {
	return setIntentStatusGuardedOn(r.pool, ctx, intentID, expected, to)
}

// refundKeyFor is the canonical idempotency key for a refund recorded from a
// provider notification.
//
// In the repository rather than the service because the lookup and the writer
// must agree on it EXACTLY. Two functions that compose the same string in two
// packages will drift, and the drift is invisible: a lookup that stops matching
// turns every replayed webhook into a second refund.
func refundKeyFor(r *Refund) string {
	if r == nil || strings.TrimSpace(r.GatewayRef) == "" {
		return ""
	}
	return fmt.Sprintf("provider:%s:%s:%.0f", r.Gateway, r.GatewayRef, r.Amount)
}

// SetIntentStatusGuardedTx is SetIntentStatusGuarded inside a transaction.
//
// It takes a Querier rather than a pgx.Tx so a service can pass whichever handle
// it holds without naming the pgx type, and so the import-boundary check
// (scripts/check-import-boundaries.mjs) can forbid pgx.Tx in a service signature
// while still permitting pgx.ErrNoRows, which a repository legitimately matches.
func (r *PaymentRepository) SetIntentStatusGuardedTx(ctx context.Context, q Querier, intentID string, expected []string, to string) error {
	return setIntentStatusGuardedOn(q, ctx, intentID, expected, to)
}

// SumRefundedByOrder is the CUMULATIVE amount already refunded for an order, and
// it is the input to the cap that stops a buyer being refunded twice.
//
// It reads the `refunds` TABLE. It used to read `wallet_transactions`:
//
//	SELECT SUM(amount) FROM wallet_transactions
//	 WHERE ref_id = $1 AND reason = 'refund' AND kind = 'credit'
//
// That is wrong now, and was catastrophically so. A refund through the GATEWAY
// never credits the buyer's wallet -- the money goes back to their card -- so this
// query returned zero after every gateway refund. The cap built specifically to
// stop over-refunding a buyer was measuring nothing on the path that actually
// refunds them, and a third partial refund was cheerfully authorised after two
// had already been paid. `refunds` is the authoritative record, for every path.
//
// Which STATES count is the whole subtlety, and it is not "everything":
//
//	pending    no -- written before the provider is called; if the submit fails,
//	             nothing moved, and counting it would refuse a legitimate retry
//	submitted  yes -- the provider accepted it and will pay
//	succeeded  yes -- the money is gone
//	failed     no  -- the provider rejected it
//	manual     yes -- we OWE the buyer this and a human must send it; not
//	             counting it would let the platform promise the same rupiah twice
//
// `q` may be the pool or an open transaction, and the caller MUST pass the
// transaction for the value to be correct under concurrency: the refund path
// locks the intent row and then re-reads this total inside the same transaction
// so a second concurrent refund sees the first one's rows. Passing the pool here
// reads on a DIFFERENT connection, outside the transaction and before the lock is
// held, which is how two partial refunds could each be individually valid and
// together exceed the charge.
//
// `excludeRefundID` is the row that is CURRENTLY BEING SETTLED, and it is
// excluded from the total.
//
// THE BUG THIS FIXES. This query counts `submitted`, and the reserve step writes
// the row as `submitted` before the provider is called. So by the time
// the settlement re-derived the cap -- after the provider had already moved the
// money -- the row being settled was counted against itself. A full refund of a
// Rp100,000 charge therefore read `already = 100,000`, computed
// `remaining = 0`, and refused itself with ALREADY_REFUNDED, rolling back the
// internal legs and the journal while the buyer's money had already gone. That
// is the single most common refund on the platform, and it failed every time.
//
// Excluding by ID is deliberately narrower than excluding by state. A row
// inserted as `pending` instead would also stop self-counting, but it would drop
// every in-flight refund out of the cap, so two concurrent gateway refunds could
// each be individually valid and together exceed the charge -- the exact race
// `03a100b` closed. An in-flight refund is money the provider has accepted and
// will pay, and it must count against a DIFFERENT refund. It must not count
// against itself.
//
// nil means "exclude nothing": the caller has no row of its own in flight, which
// is the reserve step and the return path. A pointer to an empty string is
// refused rather than treated as nil, because "no id" and "the empty id" are
// different claims and only one of them is true.
func (r *PaymentRepository) SumRefundedByOrder(
	ctx context.Context, q Querier, orderID string, excludeRefundID *string, out *float64,
) error {
	if excludeRefundID != nil && strings.TrimSpace(*excludeRefundID) == "" {
		return domain.E(domain.KindInternal, "REFUND_EXCLUDE_ID_INVALID",
			"the refund being settled was excluded from the cap without an id, so the "+
				"cap cannot be trusted; refusing rather than guessing which row was meant")
	}
	var total float64
	err := q.QueryRow(ctx, `
		SELECT COALESCE(SUM(amount), 0)::float8
		  FROM refunds
		 WHERE order_id = $1
		   AND status IN ('submitted', 'succeeded', 'manual')
		   AND ($2::uuid IS NULL OR id <> $2::uuid)`,
		orderID, uuidParam(excludeRefundID)).Scan(&total)
	if err != nil {
		return err
	}
	*out = total
	return nil
}

// uuidParam renders an optional id as something the database will accept for a
// $n::uuid parameter.
//
// A nil pointer must become SQL NULL rather than an empty string, because a
// $n::uuid parameter given an empty string is `invalid input syntax for type
// uuid` -- a query error rather than a query result, and one that aborts the
// whole refund instead of merely finding nothing. An empty sentinel that means
// "no id" is exactly the kind of value that turns a lookup into a silent
// no-match, and the replay guard was broken for three commits by one.
func uuidParam(id *string) any {
	if id == nil {
		return nil
	}
	return *id
}

// RefundByProviderKey finds a refund already recorded for a provider
// notification, by the provider's own refund reference.
//
// This is what makes a REPLAYED webhook a no-op. Providers retry: Midtrans does
// so for up to 24 hours, so a duplicate notification is the single most common
// event in the system and the one most likely to be handled wrong.
//
// Matching on the amount would be wrong in the other direction -- two genuine
// partial refunds of the same size would collapse into one and the buyer would
// silently lose the second. The provider's refund id is the only identifier it
// guarantees unique.
//
// `refunds` has no unique index on it, which is itself worth knowing: the
// guarantee here is the WHERE clause matching the fewest possible rows, and
// `refund_state_counts_toward_cap` in the service decides what happens to a
// match. A future migration should add
//
//	CREATE UNIQUE INDEX ... ON refunds (gateway, gateway_ref)
//	  WHERE gateway_ref IS NOT NULL
//
// and then this can become an INSERT ... ON CONFLICT. Until then the
// application-level check is the only guard, and it is guarded by the cap.
func (r *PaymentRepository) RefundByProviderKey(
	ctx context.Context, q Querier, intentID, key string,
) (*Refund, error) {
	if key == "" {
		return nil, nil
	}
	// The key embeds the gateway, the provider's refund reference and the amount.
	// Reconstructing it from the row rather than comparing the composed string
	// means the stored row is the source of truth, not the format of a function
	// that may change.
	var found *Refund
	rows, err := q.Query(ctx, refundSelect+`
		 WHERE payment_intent_id = $1
		   AND gateway_ref IS NOT NULL
		   AND status IN ('pending', 'submitted', 'succeeded', 'manual')
		 ORDER BY created_at DESC`, intentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	for rows.Next() {
		rf, err := scanRefund(rows)
		if err != nil {
			return nil, err
		}
		if refundKeyFor(rf) == key {
			if found == nil {
				found = rf
			}
		}
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	if found == nil {
		return nil, nil
	}
	return found, nil
}

// LockIntentForRefund takes a row lock on the payment intent and re-reads it.
//
// This is the serialisation point for every refund. The refund arithmetic reads
// the cumulative refunded total from the ledger, and that total is only correct
// if no other transaction can insert a refund row between the read and the
// write. `SELECT ... FOR UPDATE` on the intent row gives exactly that ordering,
// provided the read happens AFTER the lock -- so the whole sequence
// (lock, read total, validate, write) must be inside one transaction.
//
// The previous implementation read the total on the pool, outside the
// transaction, and then relied on a guarded UPDATE to serialise. That guard
// passes `partially_refunded` in its expected-state list, so a second
// concurrent partial refund re-evaluates the WHERE clause against the new row
// version, still matches, and proceeds. The row lock serialised the two refunds
// and then let both through.
func (r *PaymentRepository) LockIntentForRefund(ctx context.Context, q Querier, intentID string) (*domain.PaymentIntent, error) {
	in, err := scanIntent(q.QueryRow(ctx,
		`SELECT `+intentColumns+` FROM payment_intents WHERE id = $1 FOR UPDATE`, intentID))
	if err != nil {
		return nil, err
	}
	return in, nil
}

// HasEscrowRelease reports whether escrow was ever paid out for an order. A
// partially_refunded intent no longer records that, so it is read from the
// ledger row the release wrote.
// HasEscrowRelease reports whether this order's escrow was ever paid out.
//
// It takes a Querier rather than a pgx.Tx so the payment service can call it
// with its own transaction handle without naming the pgx type. That is the
// only reason this signature is not just pgx.Tx: every other "-Tx" method in
// this file is called through the OrderTx unit of work, and having one method
// that required the raw handle is what pushed pgx into the service layer's
// import list.
func (r *PaymentRepository) HasEscrowRelease(ctx context.Context, q Querier, orderID string, out *bool) error {
	var exists bool
	err := q.QueryRow(ctx, `
		SELECT EXISTS (
			SELECT 1 FROM wallet_transactions
			WHERE ref_id = $1 AND reason = $2 AND kind = 'credit'
		)`, orderID, domain.TxReasonEscrowRelease).Scan(&exists)
	if err != nil {
		return err
	}
	*out = exists
	return nil
}

func intentStatusUpdate(expected []string) string {
	q := `
		UPDATE payment_intents SET status = $3::varchar, updated_at = now(),
			captured_at = CASE WHEN $3::varchar = 'captured' THEN now() ELSE captured_at END,
			escrow_released_at = CASE WHEN $3::varchar = 'released' THEN now() ELSE escrow_released_at END,
			refunded_at = CASE WHEN $3::varchar = 'refunded' THEN now() ELSE refunded_at END
		WHERE id = $1`
	if len(expected) > 0 {
		q += ` AND status = ANY($2::varchar[])`
	}
	return q
}

func intentStatusArgs(intentID string, expected []string, status string) []any {
	args := []any{intentID}
	if len(expected) > 0 {
		args = append(args, expected)
	}
	return append(args, status)
}

func setIntentStatusOn(q interface {
	Exec(ctx context.Context, sql string, args ...any) (pgconn.CommandTag, error)
}, ctx context.Context, intentID, status string) error {
	tag, err := q.Exec(ctx, intentStatusUpdate(nil), intentStatusArgs(intentID, nil, status)...)
	if err != nil {
		return err
	}
	if tag.RowsAffected() == 0 {
		return domain.ErrNotFound
	}
	return nil
}

func setIntentStatusGuardedOn(q interface {
	Exec(ctx context.Context, sql string, args ...any) (pgconn.CommandTag, error)
}, ctx context.Context, intentID string, expected []string, to string) error {
	tag, err := q.Exec(ctx, intentStatusUpdate(expected), intentStatusArgs(intentID, expected, to)...)
	if err != nil {
		return err
	}
	if tag.RowsAffected() == 0 {
		return domain.E(domain.KindConflict, "INTENT_STATE",
			"payment intent is not in an expected state for this transition")
	}
	return nil
}

// SetIntentMethod records the concrete channel used at the gateway
// (e.g. Midtrans payment_type: gopay, qris, bank_transfer, kredivo).
func (r *PaymentRepository) SetIntentMethod(ctx context.Context, intentID, method string) error {
	_, err := r.pool.Exec(ctx,
		`UPDATE payment_intents SET method = $2, updated_at = now() WHERE id = $1`, intentID, method)
	return err
}

// Wallet fetches a wallet, creating it if absent.
func (r *PaymentRepository) Wallet(ctx context.Context, userID string) (*domain.Wallet, error) {
	var w domain.Wallet
	err := r.pool.QueryRow(ctx, `
		INSERT INTO wallets (user_id) VALUES ($1)
		ON CONFLICT (user_id) DO UPDATE SET updated_at = now()
		RETURNING user_id, balance, held_balance, created_at, updated_at`, userID).
		Scan(&w.UserID, &w.Balance, &w.HeldBalance, &w.CreatedAt, &w.UpdatedAt)
	return &w, err
}

// WalletTx applies a ledger entry, updating balance atomically.
func (r *PaymentRepository) WalletTx(ctx context.Context, userID, kind, reason string, amount float64, refID string) error {
	tx, err := r.pool.Begin(ctx)
	if err != nil {
		return err
	}
	defer tx.Rollback(ctx)
	if err := r.WalletTxOn(ctx, tx, userID, kind, reason, amount, refID); err != nil {
		return err
	}
	return tx.Commit(ctx)
}

// WalletTxOn applies a ledger entry inside a caller-managed transaction so it
// can be composed atomically with intent status changes and payouts.
func (r *PaymentRepository) WalletTxOn(ctx context.Context, q Querier, userID, kind, reason string, amount float64, refID string) error {
	if _, err := q.Exec(ctx, `
		INSERT INTO wallets (user_id) VALUES ($1) ON CONFLICT (user_id) DO NOTHING`, userID); err != nil {
		return err
	}
	var balanceAfter float64
	err := q.QueryRow(ctx, `
		UPDATE wallets SET balance = balance + CASE WHEN $2::varchar = 'debit' THEN -$3 ELSE $3 END, updated_at = now()
		WHERE user_id = $1 AND ($2::varchar <> 'debit' OR balance >= $3)
		RETURNING balance`, userID, kind, amount).Scan(&balanceAfter)
	if errors.Is(err, pgx.ErrNoRows) {
		return domain.E(domain.KindConflict, "INSUFFICIENT_BALANCE", "insufficient wallet balance")
	}
	if err != nil {
		return err
	}
	_, err = q.Exec(ctx, `
		INSERT INTO wallet_transactions (wallet_id, kind, reason, amount, balance_after, ref_id)
		VALUES ($1, $2, $3, $4, $5, NULLIF($6, ''))`,
		userID, kind, reason, amount, balanceAfter, refID)
	return err
}

// Transactions lists a wallet's ledger.
func (r *PaymentRepository) Transactions(ctx context.Context, walletID string, limit int) ([]*domain.WalletTransaction, error) {
	if limit < 1 || limit > 100 {
		limit = 20
	}
	rows, err := r.pool.Query(ctx, `
		SELECT id, wallet_id, kind, reason, amount, balance_after, COALESCE(ref_id,''), created_at
		FROM wallet_transactions WHERE wallet_id = $1 ORDER BY created_at DESC LIMIT $2`,
		walletID, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	txs := []*domain.WalletTransaction{}
	for rows.Next() {
		var t domain.WalletTransaction
		if err := rows.Scan(&t.ID, &t.WalletID, &t.Kind, &t.Reason, &t.Amount, &t.BalanceAfter, &t.RefID, &t.CreatedAt); err != nil {
			return nil, err
		}
		txs = append(txs, &t)
	}
	return txs, rows.Err()
}

// CreatePayout requests a withdrawal.
func (r *PaymentRepository) CreatePayout(ctx context.Context, p *domain.Payout) error {
	_, err := r.pool.Exec(ctx, `
		INSERT INTO payouts (id, wallet_id, amount, status, bank_name, bank_account)
		VALUES ($1, $2, $3, 'pending', NULLIF($4, ''), NULLIF($5, ''))`,
		p.ID, p.WalletID, p.Amount, p.BankName, p.BankAccount)
	return err
}

// CreatePayoutTx inserts a payout inside a caller-managed transaction.
func (r *PaymentRepository) CreatePayoutTx(ctx context.Context, tx pgx.Tx, p *domain.Payout) error {
	_, err := tx.Exec(ctx, `
		INSERT INTO payouts (id, wallet_id, amount, status, bank_name, bank_account)
		VALUES ($1, $2, $3, 'pending', NULLIF($4, ''), NULLIF($5, ''))`,
		p.ID, p.WalletID, p.Amount, p.BankName, p.BankAccount)
	return err
}

// Payouts lists payouts for a wallet.
func (r *PaymentRepository) Payouts(ctx context.Context, walletID string) ([]*domain.Payout, error) {
	rows, err := r.pool.Query(ctx, `
		SELECT id, wallet_id, amount, status, COALESCE(gateway_ref,''),
		       COALESCE(bank_name,''), COALESCE(bank_account,''), requested_at, processed_at
		FROM payouts WHERE wallet_id = $1 ORDER BY requested_at DESC`, walletID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	payouts := []*domain.Payout{}
	for rows.Next() {
		var p domain.Payout
		if err := rows.Scan(&p.ID, &p.WalletID, &p.Amount, &p.Status, &p.GatewayRef,
			&p.BankName, &p.BankAccount, &p.RequestedAt, &p.ProcessedAt); err != nil {
			return nil, err
		}
		payouts = append(payouts, &p)
	}
	return payouts, rows.Err()
}

// MarkPayoutSent is gone: it marked a payout sent WITHOUT posting a journal, so
// the money left the platform with nothing recording it. It was used by the
// sandbox auto-send path, which now goes through the service's postPayoutSettled
// so the sandbox exercises the same accounting as production. A test double that
// settles more cheaply than reality is a test double that hides the bug.

// AdminPayout is a withdrawal request joined with the requester identity.
type AdminPayout struct {
	ID          string     `json:"id"`
	WalletID    string     `json:"wallet_id"`
	UserEmail   string     `json:"user_email"`
	UserName    string     `json:"user_name"`
	Amount      float64    `json:"amount"`
	Status      string     `json:"status"`
	GatewayRef  string     `json:"gateway_ref"`
	BankName    string     `json:"bank_name"`
	BankAccount string     `json:"bank_account"`
	RequestedAt time.Time  `json:"requested_at"`
	ProcessedAt *time.Time `json:"processed_at,omitempty"`
}

// PayoutsByStatus lists withdrawal requests for the admin queue.
func (r *PaymentRepository) PayoutsByStatus(ctx context.Context, status string, limit int) ([]*AdminPayout, error) {
	if limit < 1 || limit > 200 {
		limit = 50
	}
	if status == "" {
		status = "pending"
	}
	rows, err := r.pool.Query(ctx, `
		SELECT p.id, p.wallet_id, u.email, u.full_name, p.amount, p.status,
		       COALESCE(p.gateway_ref,''), COALESCE(p.bank_name,''), COALESCE(p.bank_account,''),
		       p.requested_at, p.processed_at
		FROM payouts p
		JOIN users u ON u.id = p.wallet_id
		WHERE p.status = $1
		ORDER BY p.requested_at
		LIMIT $2`, status, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	out := []*AdminPayout{}
	for rows.Next() {
		var p AdminPayout
		if err := rows.Scan(&p.ID, &p.WalletID, &p.UserEmail, &p.UserName, &p.Amount,
			&p.Status, &p.GatewayRef, &p.BankName, &p.BankAccount,
			&p.RequestedAt, &p.ProcessedAt); err != nil {
			return nil, err
		}
		out = append(out, &p)
	}
	return out, rows.Err()
}

// PayoutForUpdate locks a pending payout and returns the details a posting
// needs.
//
// Transaction-scoped and FOR UPDATE because the payout lifecycle is two steps
// (request, then sent-or-failed) and both need the amount and the seller to post
// a journal. Reading it outside the lock is how a concurrent failure and
// completion both pass the status check.
func (r *PaymentRepository) PayoutForUpdate(ctx context.Context, q Querier, payoutID string) (*domain.Payout, error) {
	var p domain.Payout
	var processedAt *time.Time
	err := q.QueryRow(ctx, `
		SELECT id, wallet_id, amount, status, COALESCE(gateway_ref,''),
		       COALESCE(bank_name,''), COALESCE(bank_account,''), requested_at, processed_at
		  FROM payouts WHERE id = $1 AND status = 'pending' FOR UPDATE`, payoutID).
		Scan(&p.ID, &p.WalletID, &p.Amount, &p.Status, &p.GatewayRef,
			&p.BankName, &p.BankAccount, &p.RequestedAt, &processedAt)
	if errors.Is(err, pgx.ErrNoRows) {
		return nil, domain.E(domain.KindConflict, "NOT_PENDING", "payout is not awaiting processing")
	}
	if err != nil {
		return nil, err
	}
	p.ProcessedAt = processedAt
	return &p, nil
}

// MarkPayoutSentTx marks a payout sent inside a caller's transaction, so the
// status change and its ledger posting commit together.
func (r *PaymentRepository) MarkPayoutSentTx(ctx context.Context, q Querier, payoutID, ref string) error {
	tag, err := q.Exec(ctx, `
		UPDATE payouts SET status = 'sent', gateway_ref = NULLIF($2, ''), processed_at = now()
		WHERE id = $1 AND status = 'pending'`, payoutID, ref)
	if err != nil {
		return err
	}
	if tag.RowsAffected() == 0 {
		return domain.E(domain.KindConflict, "NOT_PENDING", "payout is not awaiting processing")
	}
	return nil
}

// MarkPayoutFailedTx rejects a pending payout inside a caller's transaction.
func (r *PaymentRepository) MarkPayoutFailedTx(ctx context.Context, q Querier, payoutID string) error {
	tag, err := q.Exec(ctx, `
		UPDATE payouts SET status = 'failed', processed_at = now()
		WHERE id = $1 AND status = 'pending'`, payoutID)
	if err != nil {
		return err
	}
	if tag.RowsAffected() == 0 {
		return domain.E(domain.KindConflict, "NOT_PENDING", "payout is not awaiting processing")
	}
	return nil
}

// ReserveSellerPending moves an amount out of a seller's spendable balance and
// into the payout pipeline, recording a seller_reservation row.
//
// The reservation is the fraud control, not the bookkeeping. Without it a seller
// can request a payout, and then a return comes in against the same balance and
// the reversal finds nothing to claw back -- because the money has already been
// marked as sent. Real marketplaces hold the balance until a T+n lag has passed
// with no open return or dispute.
//
// The seller_reservations row is what makes that hold visible and releasable
// rather than implicit in a balance column.
func (r *PaymentRepository) ReserveSellerPending(ctx context.Context, q Querier, sellerID, payoutID string, amount float64) error {
	if _, err := q.Exec(ctx, `
		INSERT INTO seller_reservations (seller_id, payout_id, amount, kind, note)
		VALUES ($1, $2, $3, 'payout', 'withdrawal requested')`,
		sellerID, payoutID, amount); err != nil {
		return err
	}
	return nil
}

// ReleaseSellerReservation marks a payout's reservation as released.
func (r *PaymentRepository) ReleaseSellerReservation(ctx context.Context, q Querier, payoutID string) error {
	_, err := q.Exec(ctx,
		`UPDATE seller_reservations SET released_at = now()
		  WHERE payout_id = $1 AND released_at IS NULL`, payoutID)
	return err
}

// FailPayout and CompletePayout were removed rather than left in place.
//
// They lived here and opened their own transaction, which is precisely why the
// payout lifecycle could not post a ledger journal: a repository cannot reach the
// ledger service, and a caller using these would move money with no accounting
// record and no way to add one. Leaving them would be a trap for the next
// caller, who would reasonably assume a working method does the whole job.
//
// The transaction-scoped PayoutForUpdate / MarkPayoutSentTx / MarkPayoutFailedTx
// replace them, and the service orchestrates so the journal commits with the
// status change.

// PlatformFee is the active commission configuration.
type PlatformFee struct {
	ID        string    `json:"id"`
	Pct       float64   `json:"pct"`
	Fixed     float64   `json:"fixed"`
	IsActive  bool      `json:"is_active"`
	UpdatedAt time.Time `json:"updated_at"`
}

// ActiveFee returns the active commission config.
func (r *PaymentRepository) ActiveFee(ctx context.Context) (*PlatformFee, error) {
	var f PlatformFee
	err := r.pool.QueryRow(ctx, `
		SELECT id, pct, fixed, is_active, updated_at FROM platform_fees WHERE is_active ORDER BY updated_at DESC LIMIT 1`).
		Scan(&f.ID, &f.Pct, &f.Fixed, &f.IsActive, &f.UpdatedAt)
	return &f, err
}

// SetFee updates the commission config (admin).
func (r *PaymentRepository) SetFee(ctx context.Context, pct, fixed float64) error {
	_, err := r.pool.Exec(ctx, `
		UPDATE platform_fees SET is_active = FALSE WHERE is_active = TRUE;
		INSERT INTO platform_fees (id, pct, fixed, is_active) VALUES (gen_random_uuid(), $1, $2, TRUE);`,
		pct, fixed)
	return err
}

// Commission splits an amount into platform fee and seller proceeds.
func Commission(pct, fixed, amount float64) (fee, seller float64) {
	fee = amount * pct / 100
	fee += fixed
	if fee > amount {
		fee = amount
	}
	return fee, amount - fee
}

// ApplyFee records the fee split on an intent.
func (r *PaymentRepository) ApplyFee(ctx context.Context, intentID string, fee, sellerAmount float64) error {
	_, err := r.pool.Exec(ctx, `
		UPDATE payment_intents SET fee_amount = $2, seller_amount = $3 WHERE id = $1`,
		intentID, fee, sellerAmount)
	return err
}

// ActiveFeeTx returns the active commission config inside a transaction.
func (r *PaymentRepository) ActiveFeeTx(ctx context.Context, q Querier) (*PlatformFee, error) {
	var f PlatformFee
	err := q.QueryRow(ctx, `
		SELECT id, pct, fixed, is_active, updated_at FROM platform_fees WHERE is_active ORDER BY updated_at DESC LIMIT 1`).
		Scan(&f.ID, &f.Pct, &f.Fixed, &f.IsActive, &f.UpdatedAt)
	return &f, err
}
