package repository

import (
	"context"
	"errors"
	"fmt"
	"math"
	"strings"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/vincommerce/backend/internal/db"
	"github.com/vincommerce/backend/internal/domain"
)

// PaymentRepository persists payment intents, wallets and payouts.
type PaymentRepository struct {
	pool *db.Pool
}

// NewPaymentRepository creates a PaymentRepository.
func NewPaymentRepository(pool *db.Pool) *PaymentRepository {
	return &PaymentRepository{pool: pool}
}

// Pool exposes the underlying pool for the rare caller that needs to run a
// statement outside any transaction.
//
// It exists for exactly one thing: recording a refund's outcome AFTER the gateway
// call, which cannot happen inside the transaction that reserved the refund. A
// narrower accessor (a QueryOnly method) would be the alternative, but it would
// still hand out the pool, and a method named for the pool is honest about what
// it gives away.
func (r *PaymentRepository) Pool() *db.Pool { return r.pool }

// Refund is a durable record of one attempt to return money to a buyer.
//
// It is a repository type rather than a domain one because it is a persistence
// concern: the id is generated by the application, the status set is the
// database's, and nothing in the business rules reads it as a value object.
type Refund struct {
	ID              string
	PaymentIntentID string
	OrderID         string
	JournalID       string
	Gateway         string
	GatewayRef      string
	Amount          float64
	Reason          string
	Status          string
	FailureReason   string
	RequestedBy     string
	RequestedAt     time.Time
	SettledAt       *time.Time
	CreatedAt       time.Time
}

// CreateRefund writes a refund row inside a caller's transaction.
//
// Written BEFORE the gateway is called, and committed in its own transaction, so
// that a crash between "we decided to refund" and "the provider confirmed" leaves
// a pending row reconciliation can resolve. The alternative -- call the provider
// first, record after -- loses the record exactly when it matters most: a refund
// the provider performed that this system never wrote down.
//
// gateway_ref is whatever the CALLER knows at the time, and that is not always
// nothing. This used to bind a literal empty string, on the reasoning that the
// provider's id for a refund "does not exist until the provider assigns one" --
// which is true when WE initiate a refund, and false for a refund the provider has
// already performed and told us about.
//
// The provider-notification path set GatewayRef from the notification's own refund
// id and watched it vanish, because the INSERT ignored the field:
//
//	RecordProviderRefund  -> refunds row, gateway_ref NULL
//	replayed webhook      -> lookup filters `AND gateway_ref IS NOT NULL`
//	                      -> no row can ever match
//
// So the replay guard was inert for a second, independent reason even once it was
// correctly scoped to a payment: the reference it matches on was never stored.
// `refundKeyFor` returns "" for a row with no reference, and the composed key
// never equals an incoming one. Honouring rf.GatewayRef costs the reserve path
// nothing, because reserveRefund leaves it empty and NULLIF still writes NULL.
func (r *PaymentRepository) CreateRefund(ctx context.Context, q Querier, rf *Refund) error {
	_, err := q.Exec(ctx, `
		INSERT INTO refunds (id, payment_intent_id, order_id, gateway, gateway_ref,
		                     amount, reason, status, requested_by, requested_at)
		VALUES ($1, $2, $3, $4, NULLIF($5, ''), $6, NULLIF($7, ''), $8,
		        NULLIF($9, '')::uuid, now())`,
		rf.ID, rf.PaymentIntentID, rf.OrderID, rf.Gateway, rf.GatewayRef,
		rf.Amount, rf.Reason, rf.Status, rf.RequestedBy)
	return err
}

// UpdateRefundStatus records the outcome of a gateway refund.
//
// Deliberately a bare UPDATE rather than a guarded state transition: the caller
// is reconciling an outcome it has already learned from the provider, and
// requiring a specific prior status would make recovery from an unexpected state
// impossible. The refund's own row is the record, and the terminal states are
// terminal because nothing transitions out of them.
func (r *PaymentRepository) UpdateRefundStatus(
	ctx context.Context, q Querier, refundID, gatewayRef, status, failureReason string, settledAt *time.Time,
) error {
	tag, err := q.Exec(ctx, `
		UPDATE refunds
		   SET status = $2,
		       gateway_ref = COALESCE(NULLIF($3, ''), gateway_ref),
		       failure_reason = NULLIF($4, ''),
		       settled_at = COALESCE($5::timestamptz, settled_at)
		 WHERE id = $1`,
		refundID, status, gatewayRef, failureReason, settledAt)
	if err != nil {
		return err
	}
	if tag.RowsAffected() == 0 {
		return domain.E(domain.KindNotFound, "REFUND_NOT_FOUND",
			"no refund with that id exists")
	}
	return nil
}

// SettleRefund marks a refund as successfully completed and links the journal
// that recorded the money movement.
//
// Inside the caller's transaction, so a settled refund and the money that moved
// for it are the same event rather than two that can disagree.
func (r *PaymentRepository) SettleRefund(
	ctx context.Context, q Querier, refundID, gatewayRef, status, failureReason string,
	settledAt *time.Time, raw []byte,
) error {
	tag, err := q.Exec(ctx, `
		UPDATE refunds
		   SET status = $2,
		       gateway_ref = COALESCE(NULLIF($3, ''), gateway_ref),
		       failure_reason = NULLIF($4, ''),
		       settled_at = COALESCE($5::timestamptz, now())
		 WHERE id = $1`,
		refundID, status, gatewayRef, failureReason, settledAt)
	if err != nil {
		return err
	}
	if tag.RowsAffected() == 0 {
		return domain.E(domain.KindNotFound, "REFUND_NOT_FOUND",
			"no refund with that id exists")
	}
	return nil
}

// RefundByID reads one refund.
func (r *PaymentRepository) RefundByID(ctx context.Context, refundID string) (*Refund, error) {
	return scanRefund(r.pool.QueryRow(ctx, refundSelect+` WHERE id = $1`, refundID))
}

// RefundsAwaitingGateway lists refunds whose outcome the provider still owns.
//
// These are the ones reconciliation polls. A refund in a terminal state is never
// returned, so a failed or manual refund does not get retried forever by a job
// that cannot tell the difference between "still working on it" and "a human has
// to do this".
func (r *PaymentRepository) RefundsAwaitingGateway(ctx context.Context, limit int) ([]*Refund, error) {
	if limit <= 0 {
		limit = 100
	}
	rows, err := r.pool.Query(ctx, refundSelect+`
		 WHERE status IN ('pending', 'submitted')
		 ORDER BY requested_at ASC
		 LIMIT $1`, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	out := []*Refund{}
	for rows.Next() {
		rf, err := scanRefund(rows)
		if err != nil {
			return nil, err
		}
		out = append(out, rf)
	}
	return out, rows.Err()
}

// RefundsForOrder lists an order's refunds, newest first.
func (r *PaymentRepository) RefundsForOrder(ctx context.Context, orderID string) ([]*Refund, error) {
	rows, err := r.pool.Query(ctx, refundSelect+`
		 WHERE order_id = $1 ORDER BY created_at DESC`, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	out := []*Refund{}
	for rows.Next() {
		rf, err := scanRefund(rows)
		if err != nil {
			return nil, err
		}
		out = append(out, rf)
	}
	return out, rows.Err()
}

// RefundsForAdmin lists refunds for the operator queue, joined with the order and
// buyer so the list is answerable without an N+1 per row.
//
// The join is the point. An operator triaging "who are we owed money to" needs
// the order number and the buyer's email in the same row; making them a second
// call per line is how a queue gets exported to a spreadsheet and the audit trail
// lost. The join is on the refund's own order_id, so it adds no fan-out and cannot
// duplicate a refund.
func (r *PaymentRepository) RefundsForAdmin(ctx context.Context, status string, limit int) ([]*domain.Refund, error) {
	if limit <= 0 || limit > 500 {
		limit = 100
	}
	rows, err := r.pool.Query(ctx, `
		SELECT rf.id, rf.payment_intent_id, rf.order_id, rf.gateway,
		       COALESCE(rf.gateway_ref, ''), rf.amount::float8, COALESCE(rf.reason, ''),
		       rf.status, COALESCE(rf.failure_reason, ''), COALESCE(rf.requested_by::text, ''),
		       rf.requested_at, rf.settled_at, rf.created_at,
		       COALESCE(o.order_number, ''), COALESCE(u.email, '')
		  FROM refunds rf
		  LEFT JOIN orders o ON o.id = rf.order_id
		  LEFT JOIN users  u ON u.id = o.buyer_id
		 WHERE ($1 = '' OR rf.status = $1)
		 ORDER BY rf.created_at DESC
		 LIMIT $2`, status, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	out := []*domain.Refund{}
	for rows.Next() {
		var d domain.Refund
		if err := rows.Scan(&d.ID, &d.PaymentIntentID, &d.OrderID, &d.Gateway,
			&d.GatewayRef, &d.Amount, &d.Reason, &d.Status, &d.FailureReason,
			&d.RequestedBy, &d.RequestedAt, &d.SettledAt, &d.CreatedAt,
			&d.OrderNumber, &d.BuyerEmail); err != nil {
			return nil, err
		}
		out = append(out, &d)
	}
	return out, rows.Err()
}

// refundSelectColumns is the column list shared by every read of a refund and by
// the claim's RETURNING clause, so the two cannot disagree about shape or order.
//
// Split out from refundSelect because `RETURNING` needs the columns without the
// FROM clause. Duplicating the list instead would be a second place to forget a
// column, and scanRefund's positional Scan would then fail at runtime on whichever
// path was less used.
const refundSelectColumns = `
	id, payment_intent_id, order_id, COALESCE(journal_id::text, ''),
	gateway, COALESCE(gateway_ref, ''), amount::float8, COALESCE(reason, ''),
	status, COALESCE(failure_reason, ''), COALESCE(requested_by::text, ''),
	requested_at, settled_at, created_at`

const refundSelect = `SELECT ` + refundSelectColumns + `
  FROM refunds`

// rowScanner covers both pgx.Row and pgx.Rows, so scanRefund serves the
// single-row and multi-row paths without duplicating the column order.
type rowScanner interface {
	Scan(dest ...any) error
}

func scanRefund(row rowScanner) (*Refund, error) {
	var rf Refund
	if err := row.Scan(&rf.ID, &rf.PaymentIntentID, &rf.OrderID, &rf.JournalID,
		&rf.Gateway, &rf.GatewayRef, &rf.Amount, &rf.Reason, &rf.Status,
		&rf.FailureReason, &rf.RequestedBy, &rf.RequestedAt, &rf.SettledAt, &rf.CreatedAt); err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, domain.ErrNotFound
		}
		return nil, err
	}
	return &rf, nil
}

// CreateIntent inserts a payment intent (idempotent by key).
func (r *PaymentRepository) CreateIntent(ctx context.Context, in *domain.PaymentIntent) error {
	tag, err := r.pool.Exec(ctx, `
		INSERT INTO payment_intents (id, order_id, buyer_id, amount, currency, status, gateway,
			gateway_ref, snap_token, gateway_txn_id, redirect_url, method, idempotency_key)
		VALUES ($1, $2, $3, $4, $5, $6, $7, $8, NULLIF($9,''), NULLIF($10,''), NULLIF($11,''),
			NULLIF($12, ''), $13)
		ON CONFLICT (idempotency_key) DO NOTHING`,
		in.ID, in.OrderID, in.BuyerID, in.Amount, in.Currency, in.Status, in.Gateway,
		in.GatewayRef, in.SnapToken, in.GatewayTxnID, in.RedirectURL, in.Method, in.IdempotencyKey)
	if err != nil {
		if pgErr, ok := err.(*pgconn.PgError); ok && pgErr.Code == "23505" {
			return domain.E(domain.KindConflict, "INTENT_EXISTS", "this order already has a payment intent")
		}
		return err
	}
	if tag.RowsAffected() == 0 {
		return domain.E(domain.KindConflict, "IDEMPOTENCY_REPLAY", "intent already exists for this idempotency key")
	}
	return nil
}

// CreateIntentTx inserts a payment intent inside a caller-managed transaction.
// CreateIntentTx inserts the payment intent, snapshotting the commission rate
// card in force at CHARGE time.
//
// The snapshot is what a refund later reverses. The rate used to be read at
// escrow RELEASE time from the currently-active `platform_fees` row, so an admin
// changing the rate between the order and the delivery retroactively changed what
// the seller was paid, and a refund recomputed the fee from today's rate rather
// than reversing the fee that was actually taken. See migration 00042.
//
// The rate is read HERE rather than by the caller, deliberately. There are four
// intent-creation sites (wallet, COD, gateway, and any repair path) and reading
// the rate at each of them is a chance to forget one. A refund is the only thing
// that needs the snapshot, so the write has to be unconditional.
//
// A missing rate card is not an error: the intent is created with a zero
// snapshot and commission_computed stays false, so the refund path falls back to
// the active rate. That is strictly better than failing a checkout over a
// missing configuration row, and strictly better than the retroactive
// behaviour.
func (r *PaymentRepository) CreateIntentTx(ctx context.Context, q Querier, in *domain.PaymentIntent) error {
	// Caller-supplied snapshot wins (a caller that already knows the rate, or a
	// repair path), otherwise read the active card.
	if in.CommissionRatePct == 0 && in.CommissionRateFixed == 0 {
		if cfg, err := r.ActiveFeeTx(ctx, q); err == nil && cfg != nil {
			in.CommissionRatePct = cfg.Pct
			in.CommissionRateFixed = cfg.Fixed
		}
	}
	_, err := q.Exec(ctx, `
		INSERT INTO payment_intents (id, order_id, buyer_id, amount, currency, status, gateway,
			gateway_ref, snap_token, gateway_txn_id, redirect_url, method, idempotency_key,
			commission_computed, commission_rate_pct, commission_rate_fixed)
		VALUES ($1, $2, $3, $4, $5, $6, $7, $8, NULLIF($9,''), NULLIF($10,''), NULLIF($11,''),
			NULLIF($12, ''), $13, false, $14, $15)`,
		in.ID, in.OrderID, in.BuyerID, in.Amount, in.Currency, in.Status, in.Gateway,
		in.GatewayRef, in.SnapToken, in.GatewayTxnID, in.RedirectURL, in.Method, in.IdempotencyKey,
		in.CommissionRatePct, in.CommissionRateFixed)
	if err != nil {
		if pgErr, ok := err.(*pgconn.PgError); ok && pgErr.Code == "23505" {
			return domain.E(domain.KindConflict, "INTENT_EXISTS", "this order already has a payment intent")
		}
	}
	return err
}

// ApplyFeeTx records the derived split and marks the commission computed.
//
// The boolean is set here and nowhere else. It is the predicate the refund path
// uses to decide whether the split is authoritative; before it existed the code
// used `fee_amount == 0`, which cannot distinguish "not derived" from "derived
// and genuinely zero".
func (r *PaymentRepository) ApplyFeeTx(ctx context.Context, q Querier, intentID string, fee, sellerAmount float64) error {
	_, err := q.Exec(ctx, `
		UPDATE payment_intents
		SET fee_amount = $2, seller_amount = $3, commission_computed = true, updated_at = now()
		WHERE id = $1`, intentID, fee, sellerAmount)
	return err
}

// intentColumns are the shared SELECT columns for intent lookups.
//
// The commission snapshot columns are included here rather than read separately,
// because a refund that recomputes the split from today's settings instead of
// the rate card that was in force at charge time is a silent money bug. Having
// them in the shared projection means every reader sees the same numbers.
const intentColumns = `
	id, order_id, buyer_id, amount, currency, status, gateway,
	COALESCE(gateway_ref,''), COALESCE(snap_token,''), COALESCE(gateway_txn_id,''), COALESCE(redirect_url,''),
	COALESCE(method,''), idempotency_key,
	escrow_released_at, captured_at, refunded_at, fee_amount, seller_amount,
	commission_computed, commission_rate_pct, commission_rate_fixed,
	created_at, updated_at`

func scanIntent(row pgx.Row) (*domain.PaymentIntent, error) {
	var in domain.PaymentIntent
	err := row.Scan(&in.ID, &in.OrderID, &in.BuyerID, &in.Amount, &in.Currency, &in.Status, &in.Gateway,
		&in.GatewayRef, &in.SnapToken, &in.GatewayTxnID, &in.RedirectURL,
		&in.Method, &in.IdempotencyKey,
		&in.EscrowReleasedAt, &in.CapturedAt, &in.RefundedAt, &in.FeeAmount, &in.SellerAmount,
		&in.CommissionComputed, &in.CommissionRatePct, &in.CommissionRateFixed,
		&in.CreatedAt, &in.UpdatedAt)
	if errors.Is(err, pgx.ErrNoRows) {
		return nil, domain.ErrNotFound
	}
	if err != nil {
		return nil, err
	}
	return &in, nil
}

// IntentByOrder fetches the intent for an order.
func (r *PaymentRepository) IntentByOrder(ctx context.Context, orderID string) (*domain.PaymentIntent, error) {
	in, err := scanIntent(r.pool.QueryRow(ctx,
		`SELECT `+intentColumns+` FROM payment_intents WHERE order_id = $1`, orderID))
	if domain.Is(err, domain.KindNotFound, "") {
		return nil, domain.E(domain.KindNotFound, "NO_INTENT", "no payment intent for order")
	}
	return in, err
}

// IntentByRef fetches an intent by gateway reference.
func (r *PaymentRepository) IntentByRef(ctx context.Context, gateway, ref string) (*domain.PaymentIntent, error) {
	in, err := scanIntent(r.pool.QueryRow(ctx,
		`SELECT `+intentColumns+` FROM payment_intents WHERE gateway = $1 AND gateway_ref = $2`, gateway, ref))
	if domain.Is(err, domain.KindNotFound, "") {
		return nil, domain.E(domain.KindNotFound, "NO_INTENT", "no payment intent for reference")
	}
	return in, err
}

// IntentByKey fetches an intent by its idempotency key.
func (r *PaymentRepository) IntentByKey(ctx context.Context, key string) (*domain.PaymentIntent, error) {
	in, err := scanIntent(r.pool.QueryRow(ctx,
		`SELECT `+intentColumns+` FROM payment_intents WHERE idempotency_key = $1`, key))
	if domain.Is(err, domain.KindNotFound, "") {
		return nil, domain.E(domain.KindNotFound, "NO_INTENT", "no payment intent for key")
	}
	return in, err
}

// SetIntentStatus transitions the intent status.
func (r *PaymentRepository) SetIntentStatus(ctx context.Context, intentID, status string) error {
	return setIntentStatusOn(r.pool, ctx, intentID, status)
}

// SetIntentStatusTx transitions the intent status inside the given transaction.
func (r *PaymentRepository) SetIntentStatusTx(ctx context.Context, tx pgx.Tx, intentID, status string) error {
	return setIntentStatusOn(tx, ctx, intentID, status)
}

// SetIntentStatusGuarded transitions the intent only when its current status is
// one of the expected values; returns a conflict error otherwise. This makes
// financial state machines idempotent and replay-safe.
func (r *PaymentRepository) SetIntentStatusGuarded(ctx context.Context, intentID string, expected []string, to string) error {
	return setIntentStatusGuardedOn(r.pool, ctx, intentID, expected, to)
}

// refundKeyFor is the canonical idempotency key for a refund recorded from a
// provider notification.
//
// In the repository rather than the service because the lookup and the writer
// must agree on it EXACTLY. Two functions that compose the same string in two
// packages will drift, and the drift is invisible: a lookup that stops matching
// turns every replayed webhook into a second refund.
func refundKeyFor(r *Refund) string {
	if r == nil || strings.TrimSpace(r.GatewayRef) == "" {
		return ""
	}
	return fmt.Sprintf("provider:%s:%s:%.0f", r.Gateway, r.GatewayRef, r.Amount)
}

// SetIntentStatusGuardedTx is SetIntentStatusGuarded inside a transaction.
//
// It takes a Querier rather than a pgx.Tx so a service can pass whichever handle
// it holds without naming the pgx type, and so the import-boundary check
// (scripts/check-import-boundaries.mjs) can forbid pgx.Tx in a service signature
// while still permitting pgx.ErrNoRows, which a repository legitimately matches.
func (r *PaymentRepository) SetIntentStatusGuardedTx(ctx context.Context, q Querier, intentID string, expected []string, to string) error {
	return setIntentStatusGuardedOn(q, ctx, intentID, expected, to)
}

// SumRefundedByOrder is the CUMULATIVE amount already refunded for an order, and
// it is the input to the cap that stops a buyer being refunded twice.
//
// It reads the `refunds` TABLE. It used to read `wallet_transactions`:
//
//	SELECT SUM(amount) FROM wallet_transactions
//	 WHERE ref_id = $1 AND reason = 'refund' AND kind = 'credit'
//
// That is wrong now, and was catastrophically so. A refund through the GATEWAY
// never credits the buyer's wallet -- the money goes back to their card -- so this
// query returned zero after every gateway refund. The cap built specifically to
// stop over-refunding a buyer was measuring nothing on the path that actually
// refunds them, and a third partial refund was cheerfully authorised after two
// had already been paid. `refunds` is the authoritative record, for every path.
//
// Which STATES count is the whole subtlety, and it is not "everything":
//
//	pending    no -- written before the provider is called; if the submit fails,
//	             nothing moved, and counting it would refuse a legitimate retry
//	submitted  yes -- the provider accepted it and will pay
//	succeeded  yes -- the money is gone
//	failed     no  -- the provider rejected it
//	manual     yes -- we OWE the buyer this and a human must send it; not
//	             counting it would let the platform promise the same rupiah twice
//
// `q` may be the pool or an open transaction, and the caller MUST pass the
// transaction for the value to be correct under concurrency: the refund path
// locks the intent row and then re-reads this total inside the same transaction
// so a second concurrent refund sees the first one's rows. Passing the pool here
// reads on a DIFFERENT connection, outside the transaction and before the lock is
// held, which is how two partial refunds could each be individually valid and
// together exceed the charge.
//
// `excludeRefundID` is the row that is CURRENTLY BEING SETTLED, and it is
// excluded from the total.
//
// THE BUG THIS FIXES. This query counts `submitted`, and the reserve step writes
// the row as `submitted` before the provider is called. So by the time
// the settlement re-derived the cap -- after the provider had already moved the
// money -- the row being settled was counted against itself. A full refund of a
// Rp100,000 charge therefore read `already = 100,000`, computed
// `remaining = 0`, and refused itself with ALREADY_REFUNDED, rolling back the
// internal legs and the journal while the buyer's money had already gone. That
// is the single most common refund on the platform, and it failed every time.
//
// Excluding by ID is deliberately narrower than excluding by state. A row
// inserted as `pending` instead would also stop self-counting, but it would drop
// every in-flight refund out of the cap, so two concurrent gateway refunds could
// each be individually valid and together exceed the charge -- the exact race
// `03a100b` closed. An in-flight refund is money the provider has accepted and
// will pay, and it must count against a DIFFERENT refund. It must not count
// against itself.
//
// nil means "exclude nothing": the caller has no row of its own in flight, which
// is the reserve step and the return path. A pointer to an empty string is
// refused rather than treated as nil, because "no id" and "the empty id" are
// different claims and only one of them is true.
func (r *PaymentRepository) SumRefundedByOrder(
	ctx context.Context, q Querier, orderID string, excludeRefundID *string, out *float64,
) error {
	if excludeRefundID != nil && strings.TrimSpace(*excludeRefundID) == "" {
		return domain.E(domain.KindInternal, "REFUND_EXCLUDE_ID_INVALID",
			"the refund being settled was excluded from the cap without an id, so the "+
				"cap cannot be trusted; refusing rather than guessing which row was meant")
	}
	var total float64
	err := q.QueryRow(ctx, `
		SELECT COALESCE(SUM(amount), 0)::float8
		  FROM refunds
		 WHERE order_id = $1
		   AND status IN ('submitted', 'succeeded', 'manual')
		   AND ($2::uuid IS NULL OR id <> $2::uuid)`,
		orderID, uuidParam(excludeRefundID)).Scan(&total)
	if err != nil {
		return err
	}
	*out = total
	return nil
}

// uuidParam renders an optional id as something the database will accept for a
// $n::uuid parameter.
//
// A nil pointer must become SQL NULL rather than an empty string, because a
// $n::uuid parameter given an empty string is `invalid input syntax for type
// uuid` -- a query error rather than a query result, and one that aborts the
// whole refund instead of merely finding nothing. An empty sentinel that means
// "no id" is exactly the kind of value that turns a lookup into a silent
// no-match, and the replay guard was broken for three commits by one.
func uuidParam(id *string) any {
	if id == nil {
		return nil
	}
	return *id
}

// ClaimProviderRefund records a provider refund, or returns the one already
// recorded under the same provider reference. `claimed` is false when the
// reference was already taken, and `existing` is then that row.
//
// ONE STATEMENT, BECAUSE TWO WERE A RACE. The service used to ask permission and
// then write:
//
//	already, _ := RefundByProviderKey(ctx, intentID, key)   // "not recorded"
//	if already == nil {
//	    CreateRefund(...)                                    // ...so write one
//	}
//
// Two identical webhooks arriving together both read "not recorded" and both
// inserted. Midtrans retries for up to 24 hours and does not serialise its
// retries, so this is a race the retry schedule can win -- and the loser of that
// race applies the refund a second time. A correct lookup does not help: the
// window is between the SELECT and the INSERT, and no amount of care in the Go
// closes it.
//
// `ON CONFLICT ... DO NOTHING` against the unique index from 00045 closes it in the
// database. The conflict target repeats the index's predicate, which Postgres
// requires in order to infer a PARTIAL unique index -- get it wrong and the insert
// does not deduplicate at all, which would look like a working guard and not be
// one, so it is written out rather than left to a default.
//
// An empty reference cannot be claimed. Claiming it would be meaningless -- there
// is no key to collide on -- and the unidentifiable case is escalated to an
// operator instead, so this refuses rather than inserting a row that no future
// lookup could ever match.
func (r *PaymentRepository) ClaimProviderRefund(
	ctx context.Context, q Querier, rf *Refund,
) (existing *Refund, claimed bool, err error) {
	if strings.TrimSpace(rf.GatewayRef) == "" {
		return nil, false, domain.E(domain.KindConflict, "REFUND_REFERENCE_REQUIRED",
			"a provider refund cannot be claimed without the provider's own reference; "+
				"it is the only thing that makes the refund identifiable, and therefore "+
				"the only thing that makes it safe against a replay")
	}

	inserted, err := scanRefund(q.QueryRow(ctx, `
		INSERT INTO refunds (id, payment_intent_id, order_id, gateway, gateway_ref,
		                     amount, reason, status, requested_by, requested_at)
		VALUES ($1, $2, $3, $4, NULLIF($5, ''), $6, NULLIF($7, ''), $8,
		        NULLIF($9, '')::uuid, now())
		ON CONFLICT (gateway, gateway_ref) WHERE gateway_ref IS NOT NULL
		DO NOTHING
		RETURNING `+refundSelectColumns,
		rf.ID, rf.PaymentIntentID, rf.OrderID, rf.Gateway, rf.GatewayRef,
		rf.Amount, rf.Reason, rf.Status, rf.RequestedBy))
	if err == nil {
		return inserted, true, nil
	}
	if !errors.Is(err, domain.ErrNotFound) {
		return nil, false, err
	}

	// DO NOTHING returns no row, so the conflict is the expected outcome rather
	// than an error: read back whoever holds the reference.
	existing, err = scanRefund(q.QueryRow(ctx, refundSelect+`
		 WHERE gateway = $1 AND gateway_ref = $2`,
		rf.Gateway, rf.GatewayRef))
	if err != nil {
		// The conflicting row is committed, so it must be findable. If it is not,
		// something is wrong that this caller cannot resolve by guessing -- and
		// guessing here is what applies a duplicate refund.
		return nil, false, domain.E(domain.KindInternal, "REFUND_CLAIM_CONFLICT_UNREADABLE",
			"another refund already holds this provider reference but could not be "+
				"read back; refusing rather than recording a second row for a refund "+
				"the provider has already performed")
	}
	return existing, false, nil
}

// notification, by the provider's own refund reference.
//
// This is what makes a REPLAYED webhook a no-op. Providers retry: Midtrans does
// so for up to 24 hours, so a duplicate notification is the single most common
// event in the system and the one most likely to be handled wrong.
//
// Matching on the amount would be wrong in the other direction -- two genuine
// partial refunds of the same size would collapse into one and the buyer would
// silently lose the second. The provider's refund id is the only identifier it
// guarantees unique.
//
// `refunds` has no unique index on it, which is itself worth knowing: the
// guarantee here is the WHERE clause matching the fewest possible rows, and
// `refund_state_counts_toward_cap` in the service decides what happens to a
// match. A future migration should add
//
//	CREATE UNIQUE INDEX ... ON refunds (gateway, gateway_ref)
//	  WHERE gateway_ref IS NOT NULL
//
// and then this can become an INSERT ... ON CONFLICT. Until then the
// application-level check is the only guard, and it is guarded by the cap.
func (r *PaymentRepository) RefundByProviderKey(
	ctx context.Context, q Querier, intentID, key string,
) (*Refund, error) {
	if key == "" {
		return nil, nil
	}
	// The key embeds the gateway, the provider's refund reference and the amount.
	// Reconstructing it from the row rather than comparing the composed string
	// means the stored row is the source of truth, not the format of a function
	// that may change.
	var found *Refund
	rows, err := q.Query(ctx, refundSelect+`
		 WHERE payment_intent_id = $1
		   AND gateway_ref IS NOT NULL
		   AND status IN ('pending', 'submitted', 'succeeded', 'manual')
		 ORDER BY created_at DESC`, intentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	for rows.Next() {
		rf, err := scanRefund(rows)
		if err != nil {
			return nil, err
		}
		if refundKeyFor(rf) == key {
			if found == nil {
				found = rf
			}
		}
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	if found == nil {
		return nil, nil
	}
	return found, nil
}

// LockIntentForRefund takes a row lock on the payment intent and re-reads it.
//
// This is the serialisation point for every refund. The refund arithmetic reads
// the cumulative refunded total from the ledger, and that total is only correct
// if no other transaction can insert a refund row between the read and the
// write. `SELECT ... FOR UPDATE` on the intent row gives exactly that ordering,
// provided the read happens AFTER the lock -- so the whole sequence
// (lock, read total, validate, write) must be inside one transaction.
//
// The previous implementation read the total on the pool, outside the
// transaction, and then relied on a guarded UPDATE to serialise. That guard
// passes `partially_refunded` in its expected-state list, so a second
// concurrent partial refund re-evaluates the WHERE clause against the new row
// version, still matches, and proceeds. The row lock serialised the two refunds
// and then let both through.
func (r *PaymentRepository) LockIntentForRefund(ctx context.Context, q Querier, intentID string) (*domain.PaymentIntent, error) {
	in, err := scanIntent(q.QueryRow(ctx,
		`SELECT `+intentColumns+` FROM payment_intents WHERE id = $1 FOR UPDATE`, intentID))
	if err != nil {
		return nil, err
	}
	return in, nil
}

// HasEscrowRelease reports whether escrow was ever paid out for an order. A
// partially_refunded intent no longer records that, so it is read from the
// ledger row the release wrote.
// HasEscrowRelease reports whether this order's escrow was ever paid out.
//
// It takes a Querier rather than a pgx.Tx so the payment service can call it
// with its own transaction handle without naming the pgx type. That is the
// only reason this signature is not just pgx.Tx: every other "-Tx" method in
// this file is called through the OrderTx unit of work, and having one method
// that required the raw handle is what pushed pgx into the service layer's
// import list.
func (r *PaymentRepository) HasEscrowRelease(ctx context.Context, q Querier, orderID string, out *bool) error {
	var exists bool
	err := q.QueryRow(ctx, `
		SELECT EXISTS (
			SELECT 1 FROM wallet_transactions
			WHERE ref_id = $1 AND reason = $2 AND kind = 'credit'
		)`, orderID, domain.TxReasonEscrowRelease).Scan(&exists)
	if err != nil {
		return err
	}
	*out = exists
	return nil
}

func intentStatusUpdate(expected []string) string {
	q := `
		UPDATE payment_intents SET status = $3::varchar, updated_at = now(),
			captured_at = CASE WHEN $3::varchar = 'captured' THEN now() ELSE captured_at END,
			escrow_released_at = CASE WHEN $3::varchar = 'released' THEN now() ELSE escrow_released_at END,
			refunded_at = CASE WHEN $3::varchar = 'refunded' THEN now() ELSE refunded_at END
		WHERE id = $1`
	if len(expected) > 0 {
		q += ` AND status = ANY($2::varchar[])`
	}
	return q
}

func intentStatusArgs(intentID string, expected []string, status string) []any {
	args := []any{intentID}
	if len(expected) > 0 {
		args = append(args, expected)
	}
	return append(args, status)
}

func setIntentStatusOn(q interface {
	Exec(ctx context.Context, sql string, args ...any) (pgconn.CommandTag, error)
}, ctx context.Context, intentID, status string) error {
	tag, err := q.Exec(ctx, intentStatusUpdate(nil), intentStatusArgs(intentID, nil, status)...)
	if err != nil {
		return err
	}
	if tag.RowsAffected() == 0 {
		return domain.ErrNotFound
	}
	return nil
}

func setIntentStatusGuardedOn(q interface {
	Exec(ctx context.Context, sql string, args ...any) (pgconn.CommandTag, error)
}, ctx context.Context, intentID string, expected []string, to string) error {
	tag, err := q.Exec(ctx, intentStatusUpdate(expected), intentStatusArgs(intentID, expected, to)...)
	if err != nil {
		return err
	}
	if tag.RowsAffected() == 0 {
		return domain.E(domain.KindConflict, "INTENT_STATE",
			"payment intent is not in an expected state for this transition")
	}
	return nil
}

// SetIntentMethod records the concrete channel used at the gateway
// (e.g. Midtrans payment_type: gopay, qris, bank_transfer, kredivo).
func (r *PaymentRepository) SetIntentMethod(ctx context.Context, intentID, method string) error {
	_, err := r.pool.Exec(ctx,
		`UPDATE payment_intents SET method = $2, updated_at = now() WHERE id = $1`, intentID, method)
	return err
}

// Wallet fetches a wallet, creating it if absent.
func (r *PaymentRepository) Wallet(ctx context.Context, userID string) (*domain.Wallet, error) {
	var w domain.Wallet
	err := r.pool.QueryRow(ctx, `
		INSERT INTO wallets (user_id) VALUES ($1)
		ON CONFLICT (user_id) DO UPDATE SET updated_at = now()
		RETURNING user_id, balance, held_balance, created_at, updated_at`, userID).
		Scan(&w.UserID, &w.Balance, &w.HeldBalance, &w.CreatedAt, &w.UpdatedAt)
	return &w, err
}

// WalletTx applies a ledger entry, updating balance atomically.
func (r *PaymentRepository) WalletTx(ctx context.Context, userID, kind, reason string, amount float64, refID string) error {
	tx, err := r.pool.Begin(ctx)
	if err != nil {
		return err
	}
	defer tx.Rollback(ctx)
	if err := r.WalletTxOn(ctx, tx, userID, kind, reason, amount, refID); err != nil {
		return err
	}
	return tx.Commit(ctx)
}

// WalletTxOn applies a ledger entry inside a caller-managed transaction so it
// can be composed atomically with intent status changes and payouts.
func (r *PaymentRepository) WalletTxOn(ctx context.Context, q Querier, userID, kind, reason string, amount float64, refID string) error {
	if _, err := q.Exec(ctx, `
		INSERT INTO wallets (user_id) VALUES ($1) ON CONFLICT (user_id) DO NOTHING`, userID); err != nil {
		return err
	}
	var balanceAfter float64
	err := q.QueryRow(ctx, `
		UPDATE wallets SET balance = balance + CASE WHEN $2::varchar = 'debit' THEN -$3 ELSE $3 END, updated_at = now()
		WHERE user_id = $1 AND ($2::varchar <> 'debit' OR balance >= $3)
		RETURNING balance`, userID, kind, amount).Scan(&balanceAfter)
	if errors.Is(err, pgx.ErrNoRows) {
		return domain.E(domain.KindConflict, "INSUFFICIENT_BALANCE", "insufficient wallet balance")
	}
	if err != nil {
		return err
	}
	_, err = q.Exec(ctx, `
		INSERT INTO wallet_transactions (wallet_id, kind, reason, amount, balance_after, ref_id)
		VALUES ($1, $2, $3, $4, $5, NULLIF($6, ''))`,
		userID, kind, reason, amount, balanceAfter, refID)
	return err
}

// Transactions lists a wallet's ledger.
func (r *PaymentRepository) Transactions(ctx context.Context, walletID string, limit int) ([]*domain.WalletTransaction, error) {
	if limit < 1 || limit > 100 {
		limit = 20
	}
	rows, err := r.pool.Query(ctx, `
		SELECT id, wallet_id, kind, reason, amount, balance_after, COALESCE(ref_id,''), created_at
		FROM wallet_transactions WHERE wallet_id = $1 ORDER BY created_at DESC LIMIT $2`,
		walletID, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	txs := []*domain.WalletTransaction{}
	for rows.Next() {
		var t domain.WalletTransaction
		if err := rows.Scan(&t.ID, &t.WalletID, &t.Kind, &t.Reason, &t.Amount, &t.BalanceAfter, &t.RefID, &t.CreatedAt); err != nil {
			return nil, err
		}
		txs = append(txs, &t)
	}
	return txs, rows.Err()
}

// CreatePayout requests a withdrawal.
func (r *PaymentRepository) CreatePayout(ctx context.Context, p *domain.Payout) error {
	_, err := r.pool.Exec(ctx, `
		INSERT INTO payouts (id, wallet_id, amount, status, bank_name, bank_account)
		VALUES ($1, $2, $3, 'pending', NULLIF($4, ''), NULLIF($5, ''))`,
		p.ID, p.WalletID, p.Amount, p.BankName, p.BankAccount)
	return err
}

// CreatePayoutTx inserts a payout inside a caller-managed transaction.
func (r *PaymentRepository) CreatePayoutTx(ctx context.Context, tx pgx.Tx, p *domain.Payout) error {
	_, err := tx.Exec(ctx, `
		INSERT INTO payouts (id, wallet_id, amount, status, bank_name, bank_account)
		VALUES ($1, $2, $3, 'pending', NULLIF($4, ''), NULLIF($5, ''))`,
		p.ID, p.WalletID, p.Amount, p.BankName, p.BankAccount)
	return err
}

// Payouts lists payouts for a wallet.
func (r *PaymentRepository) Payouts(ctx context.Context, walletID string) ([]*domain.Payout, error) {
	rows, err := r.pool.Query(ctx, `
		SELECT id, wallet_id, amount, status, COALESCE(gateway_ref,''),
		       COALESCE(bank_name,''), COALESCE(bank_account,''), requested_at, processed_at
		FROM payouts WHERE wallet_id = $1 ORDER BY requested_at DESC`, walletID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	payouts := []*domain.Payout{}
	for rows.Next() {
		var p domain.Payout
		if err := rows.Scan(&p.ID, &p.WalletID, &p.Amount, &p.Status, &p.GatewayRef,
			&p.BankName, &p.BankAccount, &p.RequestedAt, &p.ProcessedAt); err != nil {
			return nil, err
		}
		payouts = append(payouts, &p)
	}
	return payouts, rows.Err()
}

// MarkPayoutSent is gone: it marked a payout sent WITHOUT posting a journal, so
// the money left the platform with nothing recording it. It was used by the
// sandbox auto-send path, which now goes through the service's postPayoutSettled
// so the sandbox exercises the same accounting as production. A test double that
// settles more cheaply than reality is a test double that hides the bug.

// AdminPayout is a withdrawal request joined with the requester identity.
type AdminPayout struct {
	ID          string     `json:"id"`
	WalletID    string     `json:"wallet_id"`
	UserEmail   string     `json:"user_email"`
	UserName    string     `json:"user_name"`
	Amount      float64    `json:"amount"`
	Status      string     `json:"status"`
	GatewayRef  string     `json:"gateway_ref"`
	BankName    string     `json:"bank_name"`
	BankAccount string     `json:"bank_account"`
	RequestedAt time.Time  `json:"requested_at"`
	ProcessedAt *time.Time `json:"processed_at,omitempty"`
}

// PayoutsByStatus lists withdrawal requests for the admin queue.
func (r *PaymentRepository) PayoutsByStatus(ctx context.Context, status string, limit int) ([]*AdminPayout, error) {
	if limit < 1 || limit > 200 {
		limit = 50
	}
	if status == "" {
		status = "pending"
	}
	rows, err := r.pool.Query(ctx, `
		SELECT p.id, p.wallet_id, u.email, u.full_name, p.amount, p.status,
		       COALESCE(p.gateway_ref,''), COALESCE(p.bank_name,''), COALESCE(p.bank_account,''),
		       p.requested_at, p.processed_at
		FROM payouts p
		JOIN users u ON u.id = p.wallet_id
		WHERE p.status = $1
		ORDER BY p.requested_at
		LIMIT $2`, status, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	out := []*AdminPayout{}
	for rows.Next() {
		var p AdminPayout
		if err := rows.Scan(&p.ID, &p.WalletID, &p.UserEmail, &p.UserName, &p.Amount,
			&p.Status, &p.GatewayRef, &p.BankName, &p.BankAccount,
			&p.RequestedAt, &p.ProcessedAt); err != nil {
			return nil, err
		}
		out = append(out, &p)
	}
	return out, rows.Err()
}

// PayoutForUpdate locks a pending payout and returns the details a posting
// needs.
//
// Transaction-scoped and FOR UPDATE because the payout lifecycle is two steps
// (request, then sent-or-failed) and both need the amount and the seller to post
// a journal. Reading it outside the lock is how a concurrent failure and
// completion both pass the status check.
func (r *PaymentRepository) PayoutForUpdate(ctx context.Context, q Querier, payoutID string) (*domain.Payout, error) {
	var p domain.Payout
	var processedAt *time.Time
	err := q.QueryRow(ctx, `
		SELECT id, wallet_id, amount, status, COALESCE(gateway_ref,''),
		       COALESCE(bank_name,''), COALESCE(bank_account,''), requested_at, processed_at
		  FROM payouts WHERE id = $1 AND status = 'pending' FOR UPDATE`, payoutID).
		Scan(&p.ID, &p.WalletID, &p.Amount, &p.Status, &p.GatewayRef,
			&p.BankName, &p.BankAccount, &p.RequestedAt, &processedAt)
	if errors.Is(err, pgx.ErrNoRows) {
		return nil, domain.E(domain.KindConflict, "NOT_PENDING", "payout is not awaiting processing")
	}
	if err != nil {
		return nil, err
	}
	p.ProcessedAt = processedAt
	return &p, nil
}

// MarkPayoutSentTx marks a payout sent inside a caller's transaction, so the
// status change and its ledger posting commit together.
func (r *PaymentRepository) MarkPayoutSentTx(ctx context.Context, q Querier, payoutID, ref string) error {
	tag, err := q.Exec(ctx, `
		UPDATE payouts SET status = 'sent', gateway_ref = NULLIF($2, ''), processed_at = now()
		WHERE id = $1 AND status = 'pending'`, payoutID, ref)
	if err != nil {
		return err
	}
	if tag.RowsAffected() == 0 {
		return domain.E(domain.KindConflict, "NOT_PENDING", "payout is not awaiting processing")
	}
	return nil
}

// MarkPayoutFailedTx rejects a pending payout inside a caller's transaction.
func (r *PaymentRepository) MarkPayoutFailedTx(ctx context.Context, q Querier, payoutID string) error {
	tag, err := q.Exec(ctx, `
		UPDATE payouts SET status = 'failed', processed_at = now()
		WHERE id = $1 AND status = 'pending'`, payoutID)
	if err != nil {
		return err
	}
	if tag.RowsAffected() == 0 {
		return domain.E(domain.KindConflict, "NOT_PENDING", "payout is not awaiting processing")
	}
	return nil
}

// ReserveSellerPending moves an amount out of a seller's spendable balance and
// into the payout pipeline, recording a seller_reservation row.
//
// The reservation is the fraud control, not the bookkeeping. Without it a seller
// can request a payout, and then a return comes in against the same balance and
// the reversal finds nothing to claw back -- because the money has already been
// marked as sent. Real marketplaces hold the balance until a T+n lag has passed
// with no open return or dispute.
//
// The seller_reservations row is what makes that hold visible and releasable
// rather than implicit in a balance column.
func (r *PaymentRepository) ReserveSellerPending(ctx context.Context, q Querier, sellerID, payoutID string, amount float64) error {
	if _, err := q.Exec(ctx, `
		INSERT INTO seller_reservations (seller_id, payout_id, amount, kind, note)
		VALUES ($1, $2, $3, 'payout', 'withdrawal requested')`,
		sellerID, payoutID, amount); err != nil {
		return err
	}
	return nil
}

// ReleaseSellerReservation marks a payout's reservation as released.
func (r *PaymentRepository) ReleaseSellerReservation(ctx context.Context, q Querier, payoutID string) error {
	_, err := q.Exec(ctx,
		`UPDATE seller_reservations SET released_at = now()
		  WHERE payout_id = $1 AND released_at IS NULL`, payoutID)
	return err
}

// Seller hold reason codes written to `wallet_transactions`.
//
// One per hold KIND, not one per outcome, for two reasons. A seller seeing
// "seller_hold" on their statement cannot tell which of their orders is holding
// their money, and they will ask. And `uq_wallet_tx_business_event` is UNIQUE on
// (wallet_id, ref_id, kind, reason), so a shared reason would make a legitimate
// second hold -- a return AND a dispute on the same order -- collide on an index
// built to stop duplicate postings.
const (
	WalletReasonHoldCOD     = "hold_cod"
	WalletReasonHoldReturn  = "hold_return"
	WalletReasonHoldDispute = "hold_dispute"
	WalletReasonHoldRelease = "hold_released"
)

// WalletHeldTxOn moves money between a wallet's spendable and held balances, and
// records the movement.
//
// THIS IS THE ENFORCEMENT POINT. A hold recorded as a `seller_reservations` row
// is a note: `RequestPayout` reads `wallets.balance` and nothing else, so the money
// stayed spendable and the fraud control controlled nothing. Moving the value out
// of `balance` into `held_balance` is what makes it real, and it is why there is no
// `balance - held_balance` arithmetic in the payout path -- the transfer has
// already done it.
//
// direction is "hold" to move money out of the spendable balance, or "release" to
// move it back. Named rather than a bool, because a bool at this site is how the
// wrong sign gets posted: a released hold debiting the spendable balance would
// look like a withdrawal and no test would object.
//
// The CHECK on `wallets.held_balance >= 0` is the backstop: a release larger than
// the hold fails here rather than making the balance negative.
func (r *PaymentRepository) WalletHeldTxOn(
	ctx context.Context, q Querier, userID, direction, reason string, amount float64,
) error {
	if _, err := q.Exec(ctx, `
		INSERT INTO wallets (user_id) VALUES ($1) ON CONFLICT (user_id) DO NOTHING`, userID); err != nil {
		return err
	}

	// Signed delta on the spendable balance, signed delta on the held one. A hold
	// debits the first and credits the second; a release does the reverse. The
	// held leg is written in the same statement so the two can never disagree.
	var balanceAfter, heldAfter float64
	err := q.QueryRow(ctx, `
		UPDATE wallets
		   SET balance      = balance      + CASE WHEN $2::varchar = 'hold' THEN -$3 ELSE $3 END,
		       held_balance = held_balance + CASE WHEN $2::varchar = 'hold' THEN  $3 ELSE -$3 END,
		       updated_at = now()
		 WHERE user_id = $1
		   AND (CASE WHEN $2::varchar = 'hold'
		             THEN balance >= $3
		             ELSE held_balance >= $3 END)
		RETURNING balance, held_balance`, userID, direction, amount).Scan(&balanceAfter, &heldAfter)
	if errors.Is(err, pgx.ErrNoRows) {
		switch direction {
		case "hold":
			// The seller does not have the money to hold. That is not an internal
			// error: it means the escrow release that funds this hold has not
			// happened, which is a real and expected state for a COD order whose
			// cash is still with the courier.
			return domain.E(domain.KindConflict, "INSUFFICIENT_BALANCE",
				"there is not enough unwithdrawn balance to hold against this order")
		default:
			return domain.E(domain.KindInternal, "HELD_BALANCE_UNDERFLOW",
				"releasing a hold would take the held balance below zero, so the "+
					"reservation and the wallet disagree about how much is held")
		}
	}
	if err != nil {
		return err
	}

	// The wallet row records the movement from the SPENDABLE balance's point of
	// view, so a hold is a debit and a release a credit, whatever happened to
	// held_balance. balance_after is the spendable figure, which is the one a
	// seller reads on their statement.
	//
	// ref_id is left NULL deliberately. A hold is not a reference to an existing
	// row the way a refund references an order -- the reservation carries that --
	// and `uq_wallet_tx_business_event` is PARTIAL on `ref_id IS NOT NULL`, so a
	// NULL keeps this insert out of that index's way. Populating it with the order
	// id would make the index fire on a second hold of the same kind for the same
	// order and surface as a raw 23505.
	kind := "debit"
	if direction != "hold" {
		kind = "credit"
	}
	_, err = q.Exec(ctx, `
		INSERT INTO wallet_transactions (wallet_id, kind, reason, amount, balance_after, ref_id)
		VALUES ($1, $2, $3, $4, $5, NULL)`,
		userID, kind, reason, amount, balanceAfter)
	return err
}

// SellerReservation is a hold on a seller's money.
//
// Distinct from the row itself because the RELEASE needs the seller, the order and
// the amount: releasing a hold is not just stamping `released_at`, it moves the
// money back out of `held_balance` and posts the mirror journal, and all three
// need the same fields.
type SellerReservation struct {
	ID       string
	SellerID string
	OrderID  string
	Amount   float64
	Kind     string
	Note     string
}

// ReleasableReservations lists the holds whose conditions are met.
//
// RELEASABLE MEANS ALL OF:
//   - not already released
//   - past THAT SELLER'S lag, measured from when the hold was taken
//   - the order is COMPLETED. Not shipped, not delivered: the return window
//     opens on delivery, so releasing at delivery is releasing one day early.
//   - no open return and no open dispute against that order
//
// A set of conditions, not a timestamp, because each one is a reason a reversal
// could still arrive. A timer would release the money the moment the lag expired
// and then discover the return, which is the failure this exists to prevent.
//
// `payout` reservations are deliberately NOT included: a withdrawal's hold ends
// when the payout itself settles, which is a different event with a different
// owner, and releasing it here would free money that is still in the payout
// pipeline.
//
// THE LAG IS PER SELLER, and `platformLagDays` is only the fallback.
//
//	AND sr.created_at <= now() - make_interval(
//	        days => COALESCE(st.payout_lag_days, $1))
//
// This used to bind a single scalar, which meant an operator's `PAYOUT_LAG_DAYS`
// applied to everyone and a per-seller override was impossible without rewriting
// this query. The JOIN is on `stores.owner_id`, not on a seller id column on the
// reservation, because `seller_reservations.seller_id` references `users(id)` and
// a store is keyed on its owner -- joining the other way would silently match zero
// rows for any seller without a store, which would release nothing rather than
// something wrong, and so would go unnoticed.
//
// The SELECTs rather than UPDATEs, because the release is three writes and only the
// service can assemble them -- the repository cannot post a journal. The claim that
// makes the read-then-write safe is MarkReservationReleasedTx, which is guarded on
// `released_at IS NULL` and runs in the same transaction as the money move.
func (r *PaymentRepository) ReleasableReservations(
	ctx context.Context, q Querier, platformLagDays, limit int,
) ([]*SellerReservation, error) {
	if platformLagDays < 0 {
		return nil, domain.E(domain.KindInvalid, "RESERVATION_LAG_INVALID",
			"a payout lag cannot be negative")
	}
	if limit <= 0 {
		limit = 500
	}
	rows, err := q.Query(ctx, `
		SELECT sr.id::text, sr.seller_id::text, sr.order_id::text,
		       sr.amount::float8, sr.kind, COALESCE(sr.note, '')
		  FROM seller_reservations sr
		  JOIN orders o ON o.id = sr.order_id
		  LEFT JOIN stores st ON st.owner_id = sr.seller_id
		 WHERE sr.released_at IS NULL
		   AND sr.kind IN ('cod', 'return', 'dispute')
		   AND sr.created_at <= now() - make_interval(
		           days => COALESCE(st.payout_lag_days, $1))
		   AND o.status = 'completed'
		   AND NOT EXISTS (
		       SELECT 1 FROM return_requests r
		        WHERE r.order_id = sr.order_id
		          AND r.status IN ('requested', 'approved', 'returned')
		   )
		   AND NOT EXISTS (
		       SELECT 1 FROM disputes d
		        WHERE d.order_id = sr.order_id
		          AND d.status IN ('open', 'under_review')
		   )
		 ORDER BY sr.created_at ASC
		 LIMIT $2`, platformLagDays, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	out := []*SellerReservation{}
	for rows.Next() {
		res := &SellerReservation{}
		if err := rows.Scan(&res.ID, &res.SellerID, &res.OrderID,
			&res.Amount, &res.Kind, &res.Note); err != nil {
			return nil, err
		}
		out = append(out, res)
	}
	return out, rows.Err()
}

// SellerHeldTotal is how much money every seller currently cannot withdraw, and
// who is holding it.
//
// A hold that nobody can see is the same class of silent control as one that
// cannot be enforced. An operator watching only `escrow_outstanding` sees a number
// that does not move when a return hold is taken, and a seller asking "why is my
// balance short" has no answer the platform can produce. So this is both a total
// and the rows behind it, in one query: the total is the headline, the rows are
// what an operator actually acts on.
//
// `live` is true by default, because a released hold is history and listing it
// next to a live one invites an operator to investigate money that is already
// back. The released view exists for the same reason `settled_at` does on a
// refund: an audit trail nobody can read is not an audit trail.
func (r *PaymentRepository) SellerHeldTotal(
	ctx context.Context, q Querier, liveOnly bool, limit int,
) (float64, []*SellerHoldRow, error) {
	if limit <= 0 {
		limit = 200
	}
	rows, err := q.Query(ctx, `
		SELECT sr.seller_id::text,
		       COALESCE(sr.order_id::text, ''),
		       sr.kind,
		       COALESCE(sr.note, ''),
		       sr.amount::float8,
		       sr.created_at,
		       sr.released_at
		  FROM seller_reservations sr
		 WHERE ($1::boolean = false OR sr.released_at IS NULL)
		 ORDER BY sr.released_at NULLS FIRST, sr.created_at DESC
		 LIMIT $2`, liveOnly, limit)
	if err != nil {
		return 0, nil, err
	}
	defer rows.Close()

	total := 0.0
	out := []*SellerHoldRow{}
	for rows.Next() {
		var h SellerHoldRow
		if err := rows.Scan(&h.SellerID, &h.OrderID, &h.Kind, &h.Note,
			&h.Amount, &h.CreatedAt, &h.ReleasedAt); err != nil {
			return 0, nil, err
		}
		// A released hold is money the seller HAS, so counting it into "held"
		// would overstate the platform's restriction on itself.
		if h.ReleasedAt == nil {
			total += h.Amount
		}
		out = append(out, &h)
	}
	return moneyRound(total), out, rows.Err()
}

// moneyRound keeps the total on whole rupiah, matching every other money value in
// the system. Summing float64 and then rounding once is what keeps a total of many
// held amounts from ending in a sen the platform does not have.
func moneyRound(v float64) float64 { return math.Round(v) }

// SellerHoldRow is one hold, as an operator reads it.
type SellerHoldRow struct {
	SellerID   string     `json:"seller_id"`
	OrderID    string     `json:"order_id,omitempty"`
	Kind       string     `json:"hold_kind"`
	Note       string     `json:"note,omitempty"`
	Amount     float64    `json:"amount"`
	CreatedAt  time.Time  `json:"created_at"`
	ReleasedAt *time.Time `json:"released_at,omitempty"`
}

// MarkReservationReleasedTx claims a hold for release. Returns false when it was
// already released, which is how a second job run loses the race.
//
// `WHERE released_at IS NULL` is the whole claim, and it must be evaluated BEFORE
// the money moves. Two concurrent runs both read the same candidate; the first
// claims it, the second's UPDATE matches nothing, and the second must not then move
// the money. Same transaction as the journal and the wallet write, so a claim that
// cannot be completed leaves the hold held rather than half-released.
func (r *PaymentRepository) MarkReservationReleasedTx(ctx context.Context, q Querier, id string) (bool, error) {
	tag, err := q.Exec(ctx,
		`UPDATE seller_reservations SET released_at = now()
		  WHERE id = $1::uuid AND released_at IS NULL`, id)
	if err != nil {
		return false, err
	}
	return tag.RowsAffected() > 0, nil
}

// ReserveSellerPendingTx holds back a balance that is not yet releasable.
//
// The three non-payout kinds exist because the fraud they prevent is the same in
// each case and the timing differs. A seller who has been paid for an order that
// is still in transit, or that has an open return or dispute against it, can
// withdraw that money and leave the platform holding the reversal:
//
//	COD order, Rp500,000, delivered tomorrow, return window still open
//	seller withdraws Rp500,000 tonight
//	return approved tomorrow -> the reversal debits a wallet that is now empty
//
// `WalletTxOn` enforces balance >= 0, so the reversal does not go negative -- it
// simply fails, and the buyer's refund is stuck behind an INSUFFICIENT_BALANCE
// with no retry path. The reservation is what makes the hold real rather than
// advisory.
//
// kind is 'cod' for an order paid cash on delivery, 'return' for an open return
// claim and 'dispute' for an open dispute. Each reserves against its own order.
func (r *PaymentRepository) ReserveSellerPendingTx(
	ctx context.Context, q Querier, sellerID, orderID, kind, note string, amount float64,
) error {
	switch kind {
	case "cod", "return", "dispute":
	default:
		return domain.E(domain.KindInternal, "RESERVATION_KIND_INVALID",
			"a seller hold must be one of cod, return or dispute; an unknown kind is a "+
				"hold on money that the release job would never know how to evaluate")
	}
	if amount <= 0 {
		return domain.E(domain.KindInvalid, "RESERVATION_AMOUNT_INVALID",
			"a seller hold must reserve a positive amount")
	}
	// ON CONFLICT on the partial index from 00047, not a bare 23505.
	//
	// One live hold per order per kind, enforced by the database rather than by a
	// SELECT-then-INSERT here, because two concurrent claims on the same order both
	// read "none exists" and both insert. The index catches the loser.
	//
	// `RETURNING id` is how the outcome is known EXACTLY: a row means this call
	// inserted it, no row means the conflict fired. The alternative -- re-reading
	// the table afterwards -- is a heuristic that cannot tell a conflict from an
	// insert, and the version of this that used a one-second timestamp window was
	// exactly that.
	var id string
	err := q.QueryRow(ctx, `
		INSERT INTO seller_reservations (seller_id, order_id, amount, kind, note)
		VALUES ($1, $2, $3, $4, NULLIF($5, ''))
		ON CONFLICT (order_id, kind) WHERE order_id IS NOT NULL AND released_at IS NULL
		DO NOTHING
		RETURNING id`,
		sellerID, orderID, amount, kind, note).Scan(&id)
	if errors.Is(err, pgx.ErrNoRows) {
		// A hold of this kind is already live against this order, so the money is
		// already protected. NAMED, because the caller must be able to treat this
		// as success: a raw 23505 would fail a second return claim for a hold it
		// already has.
		return domain.E(domain.KindConflict, "SELLER_HOLD_EXISTS",
			"a hold of this kind is already live against this order, so the money is "+
				"already protected; taking a second one would hold it twice and leave "+
				"the seller short when the first is released")
	}
	return err
}

// FailPayout and CompletePayout were removed rather than left in place.
//
// They lived here and opened their own transaction, which is precisely why the
// payout lifecycle could not post a ledger journal: a repository cannot reach the
// ledger service, and a caller using these would move money with no accounting
// record and no way to add one. Leaving them would be a trap for the next
// caller, who would reasonably assume a working method does the whole job.
//
// The transaction-scoped PayoutForUpdate / MarkPayoutSentTx / MarkPayoutFailedTx
// replace them, and the service orchestrates so the journal commits with the
// status change.

// PlatformFee is the active commission configuration.
type PlatformFee struct {
	ID        string    `json:"id"`
	Pct       float64   `json:"pct"`
	Fixed     float64   `json:"fixed"`
	IsActive  bool      `json:"is_active"`
	UpdatedAt time.Time `json:"updated_at"`
}

// ActiveFee returns the active commission config.
func (r *PaymentRepository) ActiveFee(ctx context.Context) (*PlatformFee, error) {
	var f PlatformFee
	err := r.pool.QueryRow(ctx, `
		SELECT id, pct, fixed, is_active, updated_at FROM platform_fees WHERE is_active ORDER BY updated_at DESC LIMIT 1`).
		Scan(&f.ID, &f.Pct, &f.Fixed, &f.IsActive, &f.UpdatedAt)
	return &f, err
}

// SetFee updates the commission config (admin).
func (r *PaymentRepository) SetFee(ctx context.Context, pct, fixed float64) error {
	_, err := r.pool.Exec(ctx, `
		UPDATE platform_fees SET is_active = FALSE WHERE is_active = TRUE;
		INSERT INTO platform_fees (id, pct, fixed, is_active) VALUES (gen_random_uuid(), $1, $2, TRUE);`,
		pct, fixed)
	return err
}

// Commission splits an amount into platform fee and seller proceeds.
//
// The fee is rounded to whole rupiah FIRST, and the seller leg is derived as the
// residual `amount - fee`. The order matters, and getting it backwards is the bug this
// function had:
//
//	return fee, amount - fee    with fee UNROUNDED
//
// returned fractional rupiah, e.g. fee = 211.98000000000002. Postgres then rounds each
// leg independently on the way into `NUMERIC(14,2)`, so the two stored legs stopped
// summing to the charge on roughly 2.6% of orders. `payment_intents_split_sums` -- the
// constraint that exists precisely to catch money being created or destroyed at escrow
// release -- rejected them, so the order could not be settled and the SELLER WAS NOT
// PAID. A rounding bug that withholds a seller's earnings.
//
// Rounding the fee and deriving the seller as the residual makes the sum exact by
// construction, for every input, with no epsilon and no reliance on how the database
// rounds.
//
// # WHY THE PLATFORM ABSORBS THE SUB-RUPIAH REMAINDER
//
// `moneyRound` is half-away-from-zero, so the platform takes at most half a rupiah more
// than the exact percentage. Flooring instead would be marginally kinder to the seller
// and would cost the platform a rupiah per transaction, on every transaction, forever.
// Half-away-from-zero is the conventional rounding for settlement and is what the rest
// of this codebase already uses (see money.go).
//
// Bounds are enforced on the ROUNDED value, so an amount smaller than the fixed fee
// cannot produce a negative fee or a seller leg larger than the order.
func Commission(pct, fixed, amount float64) (fee, seller float64) {
	raw := amount*pct/100 + fixed
	if raw > amount {
		raw = amount
	}
	if raw < 0 {
		// A negative pct or fixed must not become a credit to the platform against the
		// seller. Config is admin-editable, so this is reachable by a typo.
		raw = 0
	}
	fee = moneyRound(raw)
	if fee > amount {
		// Only reachable if amount itself is fractional and rounds down below a fee that
		// was just under it. Clamping keeps fee + seller == amount exact.
		fee = amount
	}
	return fee, amount - fee
}

// ApplyFee records the fee split on an intent.
func (r *PaymentRepository) ApplyFee(ctx context.Context, intentID string, fee, sellerAmount float64) error {
	_, err := r.pool.Exec(ctx, `
		UPDATE payment_intents SET fee_amount = $2, seller_amount = $3 WHERE id = $1`,
		intentID, fee, sellerAmount)
	return err
}

// ActiveFeeTx returns the active commission config inside a transaction.
func (r *PaymentRepository) ActiveFeeTx(ctx context.Context, q Querier) (*PlatformFee, error) {
	var f PlatformFee
	err := q.QueryRow(ctx, `
		SELECT id, pct, fixed, is_active, updated_at FROM platform_fees WHERE is_active ORDER BY updated_at DESC LIMIT 1`).
		Scan(&f.ID, &f.Pct, &f.Fixed, &f.IsActive, &f.UpdatedAt)
	return &f, err
}

// ===========================================================================
// Payout batches
// ===========================================================================
//
// A batch GROUPS pending withdrawals so an operator can approve one day's worth
// and hand the bank a single remittance file. It does NOT pay anything.
//
// WHAT A BATCH MUST NEVER DO, and this is the whole design:
//
// It must never write `payouts.status`.
//
// `PayoutForUpdate`, `MarkPayoutSentTx` and `MarkPayoutFailedTx` ALL predicate on
// `WHERE ... AND status = 'pending'`. A batch that claimed its rows into
// `processing` would make them un-settleable AND un-failable at once, and their
// `seller_pending` balance -- credited when the withdrawal was requested, debited
// only by `payoutSettledEntries` or `payoutFailedEntries` -- would be stranded with
// no path back. The `payout` reservation would never be released either. There is
// no repair for that in the codebase.
//
// So `processing` and `cancelled` are legal values in the CHECK and are deliberately
// never written. The batch's own `status` (`draft`/`approved`/...) is the batch's
// state; the payout's state is untouched until an operator settles it through the
// existing per-payout endpoint.
//
// A test asserts that no statement in this file writes `payouts.status` other than
// the two existing transitions. That is the constraint that keeps a batch safe, and
// it is stated as a DB guarantee rather than left to the next reader's caution.

// PayoutBatch is one grouped run of withdrawals.
type PayoutBatch struct {
	ID         string
	BatchRef   string
	CutoffAt   time.Time
	Status     string
	Total      float64
	ItemCount  int
	LagDays    int
	ApprovedBy string
	ApprovedAt *time.Time
	PaidAt     *time.Time
	Note       string
	CreatedAt  time.Time
}

// Payout batch statuses, aliased from the domain vocabulary.
const (
	PayoutBatchDraft     = "draft"
	PayoutBatchApproved  = "approved"
	PayoutBatchSubmitted = "submitted"
	PayoutBatchPaid      = "paid"
	PayoutBatchFailed    = "failed"
	PayoutBatchCancelled = "cancelled"
)

// CreatePayoutBatch records the batch's receipt and returns its id.
//
// Idempotent on `batch_ref`, like `RecordSettlement` and `BeginSettlementImport`:
// a retried run must find the ORIGINAL batch rather than create a second one for the
// same cutoff, which would group the same payouts twice. The caller is told which
// happened by `created`, because "I made a batch" and "a batch was already there"
// are different things to log.
func (r *PaymentRepository) CreatePayoutBatch(
	ctx context.Context, q Querier, ref string, cutoffAt time.Time, lagDays int, note string,
) (id string, created bool, err error) {
	if strings.TrimSpace(ref) == "" {
		return "", false, domain.E(domain.KindInvalid, "PAYOUT_BATCH_REF_REQUIRED",
			"a payout batch needs a reference; it is the receipt that makes the run "+
				"re-runnable without grouping the same withdrawals twice")
	}
	err = q.QueryRow(ctx, `
		INSERT INTO payout_batches (batch_ref, cutoff_at, lag_days, status, note)
		VALUES ($1, $2, $3, 'draft', NULLIF($4, ''))
		ON CONFLICT (batch_ref) WHERE batch_ref IS NOT NULL DO NOTHING
		RETURNING id::text`, ref, cutoffAt, lagDays, note).Scan(&id)
	if errors.Is(err, pgx.ErrNoRows) {
		if err := q.QueryRow(ctx,
			`SELECT id::text FROM payout_batches WHERE batch_ref = $1`, ref).Scan(&id); err != nil {
			return "", false, err
		}
		return id, false, nil
	}
	if err != nil {
		return "", false, err
	}
	return id, true, nil
}

// UngroupedPayouts lists the withdrawals a batch may claim: pending, inside the
// cutoff, and not already an item of a batch that still stands.
//
// The NOT EXISTS is the claim. It is in the SELECT rather than trusted to the
// caller, because a batch run and a concurrent operator action are exactly the pair
// that would otherwise both decide "ungrouped" and both insert.
//
// Deliberately no `FOR UPDATE`: the caller inserts into `payout_batch_items`, and
// the unique index from 00049 on (payout_id) is what actually prevents a duplicate
// when two runs race. Locking here would hold the intent lock across a long
// grouping insert for no benefit the index does not already provide.
func (r *PaymentRepository) UngroupedPayouts(
	ctx context.Context, q Querier, cutoffAt time.Time, limit int,
) ([]*AdminPayout, error) {
	if limit <= 0 {
		limit = 500
	}
	rows, err := q.Query(ctx, `
		SELECT p.id::text, p.wallet_id::text, p.amount::float8, p.status,
		       COALESCE(p.gateway_ref,''), COALESCE(p.bank_name,''),
		       COALESCE(p.bank_account,''), p.requested_at, p.processed_at
		  FROM payouts p
		 WHERE p.status = 'pending'
		   AND p.requested_at <= $1
		   AND NOT EXISTS (
		       SELECT 1 FROM payout_batch_items i
		         JOIN payout_batches b ON b.id = i.batch_id
		        WHERE i.payout_id = p.id
		          AND b.status <> 'cancelled'
		   )
		 ORDER BY p.requested_at ASC
		 LIMIT $2`, cutoffAt, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	out := []*AdminPayout{}
	for rows.Next() {
		var p AdminPayout
		if err := rows.Scan(&p.ID, &p.WalletID, &p.Amount, &p.Status,
			&p.GatewayRef, &p.BankName, &p.BankAccount, &p.RequestedAt, &p.ProcessedAt); err != nil {
			return nil, err
		}
		out = append(out, &p)
	}
	return out, rows.Err()
}

// AddPayoutBatchItems groups withdrawals into a batch and returns how many were
// actually added.
//
// `ON CONFLICT (batch_id, payout_id) DO NOTHING` plus `RETURNING`: a row means this
// call grouped it, no row means it was already there. The count is what the worker
// logs, and it is the difference between "a batch with 40 items" and "a batch with
// 40 items that were already counted" -- reporting the attempted number would make a
// re-run look like it did work.
func (r *PaymentRepository) AddPayoutBatchItems(
	ctx context.Context, q Querier, batchID string, items []*AdminPayout,
) (int, error) {
	added := 0
	for _, p := range items {
		tag, err := q.Exec(ctx, `
			INSERT INTO payout_batch_items (batch_id, payout_id, seller_id, amount, status)
			VALUES ($1, $2::uuid, $3::uuid, $4, 'pending')
			ON CONFLICT (batch_id, payout_id) DO NOTHING`,
			batchID, p.ID, p.WalletID, p.Amount)
		if err != nil {
			return added, err
		}
		if tag.RowsAffected() > 0 {
			added++
		}
	}
	return added, nil
}

// RecountPayoutBatch refreshes the cached totals after items change.
//
// Recomputed from the ITEMS rather than incremented by the caller, because an
// incremental counter and the rows can disagree after a retried run, and a
// `total` that disagrees with its own items is a number an operator will trust in
// the approval step and be wrong by.
func (r *PaymentRepository) RecountPayoutBatch(ctx context.Context, q Querier, batchID string) error {
	_, err := q.Exec(ctx, `
		UPDATE payout_batches b
		   SET total = COALESCE(agg.sum, 0),
		       item_count = COALESCE(agg.n, 0)
		  FROM (
		      SELECT batch_id, SUM(amount) AS sum, COUNT(*) AS n
		        FROM payout_batch_items WHERE batch_id = $1 GROUP BY batch_id
		  ) agg
		 WHERE b.id = $1::uuid`, batchID)
	return err
}

// ApprovePayoutBatchTx moves a draft batch to approved, recording who and when.
//
// Guarded on `status = 'draft'`, so approving twice is a conflict rather than a
// second approval. It touches ONLY the batch. `payouts` is not read and not written
// -- see the section comment above.
func (r *PaymentRepository) ApprovePayoutBatchTx(
	ctx context.Context, q Querier, batchID, approvedBy string,
) (int, string, error) {
	var (
		status    string
		itemCount int
	)
	err := q.QueryRow(ctx, `
		UPDATE payout_batches
		   SET status = 'approved', approved_by = $2::uuid, approved_at = now()
		 WHERE id = $1::uuid AND status = 'draft'
		RETURNING status, item_count`, batchID, approvedBy).Scan(&status, &itemCount)
	if errors.Is(err, pgx.ErrNoRows) {
		return 0, "", domain.E(domain.KindConflict, "PAYOUT_BATCH_NOT_DRAFT",
			"this batch is not a draft, so it cannot be approved; a batch that is "+
				"already approved does not need approving twice")
	}
	if err != nil {
		return 0, "", err
	}
	return itemCount, status, nil
}

// PayoutBatchByID reads one batch.
func (r *PaymentRepository) PayoutBatchByID(ctx context.Context, q Querier, batchID string) (*PayoutBatch, error) {
	var b PayoutBatch
	err := q.QueryRow(ctx, `
		SELECT id::text, COALESCE(batch_ref,''), cutoff_at, status, total::float8,
		       item_count, lag_days, COALESCE(approved_by::text,''), approved_at,
		       paid_at, COALESCE(note,''), created_at
		  FROM payout_batches WHERE id = $1::uuid`, batchID).
		Scan(&b.ID, &b.BatchRef, &b.CutoffAt, &b.Status, &b.Total, &b.ItemCount,
			&b.LagDays, &b.ApprovedBy, &b.ApprovedAt, &b.PaidAt, &b.Note, &b.CreatedAt)
	if errors.Is(err, pgx.ErrNoRows) {
		return nil, domain.ErrNotFound
	}
	if err != nil {
		return nil, err
	}
	return &b, nil
}

// PayoutBatches lists batches newest first. Empty status means all.
func (r *PaymentRepository) PayoutBatches(ctx context.Context, q Querier, status string, limit int) ([]*PayoutBatch, error) {
	if limit <= 0 {
		limit = 100
	}
	rows, err := q.Query(ctx, `
		SELECT id::text, COALESCE(batch_ref,''), cutoff_at, status, total::float8,
		       item_count, lag_days, COALESCE(approved_by::text,''), approved_at,
		       paid_at, COALESCE(note,''), created_at
		  FROM payout_batches
		 WHERE ($1::varchar = '' OR status = $1::varchar)
		 ORDER BY cutoff_at DESC, created_at DESC
		 LIMIT $2`, status, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	out := []*PayoutBatch{}
	for rows.Next() {
		var b PayoutBatch
		if err := rows.Scan(&b.ID, &b.BatchRef, &b.CutoffAt, &b.Status, &b.Total,
			&b.ItemCount, &b.LagDays, &b.ApprovedBy, &b.ApprovedAt, &b.PaidAt,
			&b.Note, &b.CreatedAt); err != nil {
			return nil, err
		}
		out = append(out, &b)
	}
	return out, rows.Err()
}

// PayoutBatchRemittance lists the rows a remittance file is built from, with the
// bank details the file needs.
//
// Ordered by seller then payout so two exports of the same batch are byte-identical,
// which is what makes one of them auditable against the other. A remittance file
// whose order depends on a plan choice is a file nobody can diff.
func (r *PaymentRepository) PayoutBatchRemittance(
	ctx context.Context, q Querier, batchID string,
) ([]*AdminPayout, error) {
	rows, err := q.Query(ctx, `
		SELECT p.id::text, p.wallet_id::text, i.amount::float8, i.status,
		       COALESCE(p.gateway_ref,''), COALESCE(p.bank_name,''),
		       COALESCE(p.bank_account,''), p.requested_at, NULL::timestamptz
		  FROM payout_batch_items i
		  JOIN payouts p ON p.id = i.payout_id
		 WHERE i.batch_id = $1::uuid
		 ORDER BY p.wallet_id, p.requested_at, p.id`, batchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	out := []*AdminPayout{}
	for rows.Next() {
		var p AdminPayout
		if err := rows.Scan(&p.ID, &p.WalletID, &p.Amount, &p.Status,
			&p.GatewayRef, &p.BankName, &p.BankAccount, &p.RequestedAt, &p.ProcessedAt); err != nil {
			return nil, err
		}
		out = append(out, &p)
	}
	return out, rows.Err()
}
